### ISSUE TITLE
Connection aliases not supported in 

### ISSUE THREAD

**Issue by ThijsFeryn** [nrk/predis#219]
The *Predis\Connection\Aggregate\RedisCluster'* class in version 1.0.1-dev doesn't support aliases when performing a *getConnectionsById* call. Instead it uses a host and port combination.

Would it be possible to just use the *Predis\Connection\Aggregate\PredisCluster* behaviour? Or would that break other features in RedisCluster?

Thanks
Thijs

**Comment by ThijsFeryn** [comment]
I was playing around with the master-slave replication features and noticed you can easily get the master or slave based on the alias.

I know that Redis Cluster doesn't require you to send your writes to the master because it distributes requests internally. But it could be interesting to be able to select a specific node based on an alias.

Use cases could be: 

* Load distribution
* Geodistribution
* Remaining compatible when an master-slave setup is replaced by a cluster setup.

**Comment by nrk** [comment]
I'm closing this issue since there's no predictable way to pre-assign aliases to nodes with both redis-cluster and redis-sentinel, I prefer to avoid having a feature if it's half-baked or produces inconsistent results.
