### ISSUE TITLE
Predis does not support saving empty values

### ISSUE THREAD

**Issue by Ocramius** [nrk/predis#241]
See https://travis-ci.org/doctrine/cache/jobs/58527174#L591

Related: doctrine/cache#67

**Comment by arjank** [comment]
I don't think this is a Predis issue. Doctrine tries/tried to store an array into something that only holds strings. Adding logic to cast arrays to strings (and objects to strings too) would cause a lot of problems in trying to keep track of what is what, and/or a lot of overhead. If you want to be able to store are retrieve items that are not strings in their original form, you should write a wrapper for Predis to handle your specific use case.

**Comment by nrk** [comment]
For how much I understand about the reason behind this issue, I agree with @arjank. It's still possible to serialize the value before passing it to the client, or define a new command handler to be injected in the server profile used by Predis so that everything is handled transparently.
