### ISSUE TITLE
Connection to a Redis cluster

### ISSUE THREAD

**Issue by Innovaction24** [nrk/predis#242]
Hi all,

I have on one machine a Redis cluster with 3 masters and three slaves, master are on ports 8000..8002,
slaves on 8003..8005. I've added some values that are stored on different masters. If I specify all masters
in the connection, everything is working great, if I only specify one master, I get an exception:

No connection could be made because the target machine actively refused it. [tcp://127.0.0.1:8001]

Why is it not able to connect to the 8001 node ? predis does seem to know to go to the 8001 for the other keys (I'm connecting to the 8002 node)

Code:
require 'predis/autoload.php';

//$parameters = ['tcp://10.240.2.199:8000', 'tcp://10.240.2.199:8001', 'tcp://10.240.2.199:8002']; // this works
$parameters = ['tcp://10.240.2.199:8002']; // this fails if I retrieve keys that are no on 8002
$options    = ['cluster' => 'redis'];

$client = new Predis\Client($parameters, $options);

//$client->set('foo', 'bar');
$value = $client->get('foo');
echo($value.'<br/>');

$value = $client->get('klomp');
echo($value.'<br/>');

$value = $client->get('jan');
echo($value.'<br/>');

$value = $client->get('auto');
echo($value.'<br/>');

Thanks,
Michiel

**Comment by nrk** [comment]
The error message says that it's trying to connect to `tcp://127.0.0.1:8001`, so unless it's not an issue with the `$parameters` you are passing to the client I can't think of any valid reason where that host:port pair comes from (I doubt it comes from a `-MOVED` or `-ASK` response, it shouldn't be possible AFAIK).
