### ISSUE TITLE
Installation and inclusion via composer

### ISSUE THREAD

**Issue by gioialorusso** [nrk/predis#243]
Hi there,
I installed the predis lib via composer. Can you tell me how can I include it with the "use" statement (like use Predis\Autoloader ...) I cannot figure out how to include it.
Thanks.

**Comment by SpacePossum** [comment]
Hi,
After installing the package using composer make sure you `require` the `autoload.php` file in php script you are running. The `autoload.php` should be generated by `composer` for you. Most of the times it is in `vendor/autoload.php`.

If you have that one included (`require`-ed) you can start using `predis` with:

`use Predis\Client;`

and follow the samples from the readme (https://github.com/nrk/predis/blob/v1.0/README.md)
