### ISSUE TITLE
Interface 'Predis\Configuration\OptionsInterface' not found

### ISSUE THREAD

**Issue by ronakthamor** [nrk/predis#244]
Sometimes, I am getting this error:

    PHP Fatal error:  Interface 'Predis\Configuration\OptionsInterface' not found in
    D:\home\site\wwwroot\application\predis\src\Configuration\Options.php on line 23

It crashes the server and I am getting HTTP errors on it. I can not access website then after for a while. Website is running on windows azure. Let me know if you need more information regarding this.

I checked Options.php file on server. It's already there. So, Why am I getting not found error? And why it causes HTTP server errors?

**Comment by nrk** [comment]
Aside from a blatant error in your scripta misconfiguration of your host or a bug in the specific version of PHP used on your azure VM, I can't think of any valid reason for why PHP's autoloader fails to load `Predis\Configuration\OptionsInterface`. Are you using [Composer](https://getcomposer.org/) to manage the dependencies of your project? If not, you should read about [how to correctly load the library](https://github.com/nrk/predis#loading-the-library).
