### ISSUE TITLE
Del command key(s) arguments(s)

### ISSUE THREAD

**Issue by Aliance** [nrk/predis#250]
http://redis.io/commands/del
```php
// src/ClientInterface.php
 * @method int    del(array $keys)
```

This phpdoc is not suitable for this code:
```php
$Client->del('oneStringKey');
```

PHPStorm highlights this line, telling that 'expected array string is given'. Any ideas?

**Comment by Aliance** [comment]
Also `sadd`, `spop`, etc...

**Comment by dnmurray** [comment]
What I noticed was the inconsistency in the phpdoc comments:
    @method int    sadd($key, array $members)
    @method int    srem($key, $member)
Turns out the methods do the right thing, whether a scalar or array is passed as an argument.  Looks like a phpdoc limitation.  How do you represent that either a scalar or an array may be passed?

**Comment by SpacePossum** [comment]
>How do you represent that either a scalar or an array may be passed?

You can't type hint two types for one param in a method signature AFAIK. The type hint should be removed and the hint for developers should be placed in the PHPDoc for the method itself.

However I think Predis is just nice to the developers here, the correct way to use this method (and make PHPStorm happy) is to call it like:

```php
$Client->del(array('oneStringKey)');
```

**Comment by nrk** [comment]
Unfortunately this is indeed a limitation of phpdoc as it's not possible to specify different signatures for the same method. When the addition of @method tags was requested in the past, we have quite [a long exchange of comments](https://github.com/nrk/predis/issues/89) to find a decent compromise and this is what we concluded was the best approach. It's still something that doesn't feel right to me, but we can't do much about it anyway :-(
