### ISSUE TITLE
Method spop supports second argument count since redis 3.2

### ISSUE THREAD

**Issue by Aliance** [nrk/predis#251]
http://redis.io/commands/spop

> Count argument extension
> Redis 3.2 will be the first version where an optional count argument can be passed to SPOP in order to retrieve multiple elements in a single call. The implementation is already available in the unstable branch.

Will you plan to make the ability to use this argument?

**Comment by nrk** [comment]
@Aliance it's already possible to leverage the additional count argument for the [`SPOP` command](http://redis.io/commands/spop) simply by doing `$client->spop($key, $count)`, no change is needed in Predis to support it in this case.

**Comment by AnatolyAstapov** [comment]
return $this->redis->spop($this->listName, 100);
Predis\Response\ServerException: ERR wrong number of arguments for 'spop'
redis 3.0

**Comment by SpacePossum** [comment]
@AnatolyAstapov please be aware that the second argument is not available for Redis 3.0

@see http://redis.io/commands/spop
>The count argument will be available in a later version and is not available in 2.6, 2.8, 3.0
