### ISSUE TITLE
Sscan freeze on empty set

### ISSUE THREAD

**Issue by dummas** [nrk/predis#253]
* Predis 1.0.1
* redis_version: 3.0.0
* PHP 5.5.9-1ubuntu4.9 (fpm-fcgi) (built: Apr 17 2015 11:44:58)
* Linux 3.13.0-52-generic #85-Ubuntu SMP Wed Apr 29 16:44:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```
$ redis-cli -c -p 30001
$ localhost:30001> get namespace:key
$ (nil)
$ localhost:30001>
```

```
$members = $client->scard($namespace . ':' . $key); // $members = 0;

foreach (new SetKey($client, $namespace . ':' . $key) as $data) // freezes
{
  ...
}
```

**Comment by nrk** [comment]
That's quite strange as I can't replicate the issue in any way. Can you provide the output of `MONITOR` run inside `redis-cli` when running this PHP script?

**Comment by nrk** [comment]
@dummas I'm closing this issue since I'm not able to replicate it in any way even using the same versions of Predis, Redis and PHP. Feel free to re-open it if you have more details.
