### ISSUE TITLE
Unintended keys with TTL = -1

### ISSUE THREAD

**Issue by s-d-p** [nrk/predis#255]
We're seeing keys with `-1` in our redis cache but after thoroughly examining the code base we cannot see any possible way for the -1 to get passed as a value. Is this possibly a bug in predis? Or is there a situation where assigning TTL `-1` unexpectedly might be the intended behavior?

**Comment by nrk** [comment]
As stated in the Redis documentation for the [`TTL` command](http://redis.io/commands/ttl):

> Starting with Redis 2.8 the return value in case of error changed:
The command returns -2 if the key does not exist.
The command returns -1 if the key exists but has no associated expire.
