### ISSUE TITLE
Set options for ZADD command in laravel redis

### ISSUE THREAD

**Issue by baao** [nrk/predis#256]
I'm trying to set options for ZADD with laravel redis but am failing.

The option I need to set is NX, as stated in the documentation:

    ZADD options (Redis 3.0.2 or greater)

    ZADD supports a list of options, specified after the name of the key and before the first score argument.

So I wrote it like this:

    $this->redis->zAdd('orderIDs:' . $category, 'NX',[$orderId => $timestamp[1]]);

The error message I get is

    PHP warning: strlen() expects parameter 1 to be string, array given in /RediMail/vendor/predis/predis/src/Connection/StreamConnection.php on line 270

**Comment by nrk** [comment]
Hi baao,

Those modifiers for the [`ZADD` command](http://redis.io/commands/zadd) have been added very recently in Redis (3.0.2 released 18 days ago) and Predis does not support them yet, at least not when using the "simplified signature" which is actually just client-side simplification.

In the meanwhile you can use `$client->zadd($key, 'NX', $timestamp1, $orderId)` following the same signature as defined by the Redis documentation, just like any other command.

**Comment by nrk** [comment]
I've just [pushed a commit](https://github.com/nrk/predis/commit/354d1ef921f94b67d9e51cb59391bacc414669e7) to support the modifiers of [`ZADD`](http://redis.io/commands/zadd) when passing a named array for score-member pairs
