### ISSUE TITLE
Smart client issue

### ISSUE THREAD

**Issue by Emdis** [nrk/predis#262]
Hi,

I have a Redis Cluster with 3 master nodes and 3 slave ones.
I'm using Predis version '1.0.1' and Redis 3.0.1
Here is my code below:

<?php
require "/opt/php/vendor/predis/autoload.php";
Predis\Autoloader::register();

try {

$parameters = array('tcp://X.X.X.X/?password=secret', 'tcp://Y.Y.Y.Y/?password=secret','tcp://Z.Z.Z.Z/?password=secret');

$options = array("cluster", "redis");
$redis = new Predis\Client(
        $parameters
        , $options);

    echo $redis->set('test','It works !') .PHP_EOL;
    echo "Successfully connected to Redis";

}
catch (Exception $e) {
    echo "Couldn't connect to Redis" .PHP_EOL;
    echo $e->getMessage() .PHP_EOL;
$pos =strpos((string)$e->getMessage(), 'MOVED');
        if ($pos === false)
        echo "Understood" .PHP_EOL;
else
        echo "Needs to relaunch with new server" .PHP_EOL;

$pattern = '/MOVED (\d+) ([\d\.]+)\:(\d+)/';
preg_match($pattern, (string)$e->getMessage(), $matches, PREG_OFFSET_CAPTURE);
$parameters = array((string)('tcp://' . $matches[2][0] . '/?password=secret'));
$redis = new Predis\Client(
        $parameters
        , $options));

echo $redis->set('test','It works !') .PHP_EOL;
?>
Here is what I'm getting when I launch my php code:

Couldn't connect to Redis
MOVED 15495 Z.Z.Z.Z:6379
Needs to relaunch with new server
OK

So I would like to know what I'm doing wrong for the client to automatically handle -MOVED or -ASK responses coming from Redis nodes please.

Thanks a lot !

**Comment by nrk** [comment]
Please don't open another issue when the very same matter is being dealt with in another one, albeit closed (see #259). Thanks.
