### ISSUE TITLE
Random connection time out using Redis cluster

### ISSUE THREAD

**Issue by Emdis** [nrk/predis#263]
Hi guys,

We're using Predis 1.0.1 in Cluster mode (3 masters, 3 slaves) to connect to our Production Redis Platform (Redis 3.0.1) and we are having a weird issue.
We're having random connection time out, we checked obvious things like memory and/or CPU and/or IO and/or Network overload but found nothing.

(07/07/15 12:15:14PM) [12949] ultraErrorHandler(): Fatal PHP error: 2, message: stream_socket_client(): unable to connect to tcp://X.X.X.X:6379 (Connection timed out), file: /opt/php/vendor/predis/src/Connection/StreamConnection.php, line 82 [12949] Ultra\Lib\Util\Redis::get(): Connection timed out [tcp://X.X.X.X:6379]

We're having those errors even with low traffic so we checked the Redis connection refused counts but it reads 0 so we assume that for whatever reason Predis is not even able to reach the cluster.

We tried several combination of timeout (0 then -1 then 600) with read_write_timeout=-1 but no luck.
This is what we see from a code perspective
We tried:
[parameters:Predis\Connection\Parameters:private] => Array
                                                                (
                                                                    [scheme] => tcp
                                                                    [host] => X.X.X.X
                                                                    [port] => 6379
                                                                    [path] => /
                                                                    [password] => ****
                                                                    [read_write_timeout] => -1
                                                                    [timeout] => 5
                                                                )

but also
[parameters:Predis\Connection\Parameters:private] => Array
                                                                (
                                                                    [scheme] => tcp
                                                                    [host] => X.X.X.X
                                                                    [port] => 6379
                                                                    [path] => /
                                                                    [password] => ****
                                                                    [read_write_timeout] => -1
                                                                    [timeout] => 0
                                                                )

Here is how we initiate our connection string with Predis

$parameters = array('tcp://X.X.X.X/?password=secret&read_write_timeout=-1&timeout=0', 'tcp://Y.Y.Y.Y/?password=secret&read_write_timeout=-1&timeout=0','tcp://Z.Z.Z.Z/?password=secret&read_write_timeout=-1&timeout=0');

$options = array("cluster", "redis");
$redis = new Predis\Client(
        $parameters
        , $options);

Could you help us please?

Thanks a lot !!!!

**Comment by nrk** [comment]
I can't think of anything directly attributable to Predis, but just be aware of the fact that master-slave configurations are currently not yet supported with redis-cluster (working on it for the next minor release) so you must rewrite the client parameters (manually or automatically, it's up to you) accordingly whenever a slave is promoted to master. Could it be that the client is trying to reach a dead node?

PS: `read_write_timeout` is useless in you case since it's the timeout for read and write operations once the connection has been established, which is not the case when you are having these issues.

**Comment by Ewan-GrandSlam** [comment]
If you are getting many connect timeouts, change your redis cluster setting (timeout) to 300s "CONFIG SET timeout 300" - redis cluster is behaving improperly when a low or no timeout is specified in your cluster config.

**Comment by Emdis** [comment]
Thanks for the hint on Redis Cluster !! Appreciate it

**Comment by nrk** [comment]
Any update on your issue @Emdis?
