### ISSUE TITLE
Pipelining with redis-cluster throws exception

### ISSUE THREAD

**Issue by romanm485** [nrk/predis#267]
It is not possible to use pipelining when using redis-cluster.

predis-version: 1.0.2-dev
redis-version: 3.0.2
php-version: 5.6.9-0+deb8u1
os: Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux

This works fine:

    $parameters = ['tcp://10.9.200.51:47801', 'tcp://10.9.200.52:47801', 'tcp://10.9.200.53:47801', 'tcp://10.9.200.54:47801'];
    $options    = ['cluster' => 'redis'];

    $redis = new Predis\Client($parameters, $options);

    for($i = 0; $i < 10; $i++)
    {
        $rand = mt_rand(1111111,9999999);
        $k = 'test_'.$rand;
        try{
            $redis->set($k, 1);
        }
        catch(Exception $ex)
        {
            print_r($ex);
        }
    }

This does not work:

    $parameters = ['tcp://10.9.200.51:47801', 'tcp://10.9.200.52:47801', 'tcp://10.9.200.53:47801', 'tcp://10.9.200.54:47801'];
    $options    = ['cluster' => 'redis'];

    $redis = new Predis\Client($parameters, $options);

    $pipe = $redis->pipeline();

    for($i = 0; $i < 10; $i++)
    {
        $rand = mt_rand(1111111,9999999);
        $k = 'test_'.$rand;
        try{
            $pipe->set($k, 1);
            $pipe->expire($k, 10);
        }
        catch(Exception $ex)
        {
            print_r($ex);
        }
    }

    $pipe->execute();

You get this exception:

    PHP Fatal error:  Uncaught exception 'Predis\Response\ServerException' with message 'MOVED 7276 10.9.200.61:47902' in /var/www/predis_test/Predis/Pipeline/Pipeline.php:105
    Stack trace:
    #0 /var/www/predis_test/Predis/Pipeline/Pipeline.php(149): Predis\Pipeline\Pipeline->exception(Object(Predis\Connection\Aggregate\RedisCluster), Object(Predis\Response\Error))
    #1 /var/www/predis_test/Predis/Pipeline/Pipeline.php(168): Predis\Pipeline\Pipeline->executePipeline(Object(Predis\Connection\Aggregate\RedisCluster), Object(SplQueue))
    #2 /var/www/predis_test/Predis/Pipeline/Pipeline.php(217): Predis\Pipeline\Pipeline->flushPipeline()
    #3 /var/www/predis_test/lasttest.php(31): Predis\Pipeline\Pipeline->execute()
    #4 {main}
      thrown in /var/www/predis_test/Predis/Pipeline/Pipeline.php on line 105

**Comment by nrk** [comment]
Unfortunately it's not possibile to rely on pipelines when using redis-cluster due to their inner working and the fact that slot migrations may happen. See (this old discussion)[https://groups.google.com/forum/#!topic/redis-db/4I0ELYnf3bk] on the redis mailing list for details.
