### ISSUE TITLE
Regression on HHVM with update to 1.0.2

### ISSUE THREAD

**Issue by keiosweb** [nrk/predis#269]
Hi there,

We are using predis/predis with laravel 5.0 / OctoberCMS running in hhvm 3.7.x. Update to 1.0.2 causes:
http://i.keios.eu/snapshot-20150730-154847.png

This does not happen with 1.0.1. Any clue what might be the reason?

**Comment by nrk** [comment]
> No description provided.

Not even what kind of regression and which version of HHVM?

**Comment by keiosweb** [comment]
Sorry, pressed enter by mistake, edited first post with information ;)

**Comment by nrk** [comment]
Unfortunately I won't be able to test on HHVM until later today but I have a guess right now: could you try replacing [this line](https://github.com/nrk/predis/blob/v1.0.2/src/Connection/StreamConnection.php#L77) by changing the code from:

```
$uri = "tcp://[$parameters->host]:$parameters->port";
```

to the following (note the lack of square brackets):

```
$uri = "tcp://$parameters->host:$parameters->port";
```

This change is to support IPv6 embedded address literals but works for IPv4 anyway when running on the _standard_ PHP interpreter.

**Comment by keiosweb** [comment]
Yep, change in this line fixes this.

**Comment by keiosweb** [comment]
This is a tricky issue with HHVM, there was a long list of incompatibilites with socket functions: https://github.com/facebook/hhvm/issues?utf8=%E2%9C%93&q=is%3Aissue+socket

I believe it would be a good idea to solve this on two levels: a hotfix issued with 1.0.3 version with code similar to this:

    if (defined('HHVM_VERSION')) {
        $uri = "tcp://$parameters->host:$parameters->port";
    } else {
        $uri = "tcp://[$parameters->host]:$parameters->port";
    }

Second step would be to create an issue in hhvm repo, since they are tracking all incompatiblities with Zend Engine. That code could be unified to version from 1.0.2 when they fix this on their side.

What do you think?

**Comment by nrk** [comment]
Take an hotfix for granted, but I'd prefer using `!filter_var($parameters->host, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)` because square brackets are __mandatory__ for IPv6 literal addresses in URI strings.

This patch will solve the problem in the case of IPv4 addresses and hostnames, but if HHVM has problems with IPv6 addresses in square brackets for the first argument of `stream_socket_client()` then it's more like a serious bug a not a matter of incompatibilities with PHP. I guess this is not the case but I'm waiting to do a quick test to have a confirmation before doing anything, I'll create an issue on HHVM's repository after that.

**Comment by nrk** [comment]
Alright now I can confirm that everything works fine with IPv6 addresses being enclosed in square brackets (like it should be after all) so it's only an incompatibility between HHVM and PHP in how IPv4 and hostname are treated when eclosed in square brackets (PHP accepts them while HHVM apparently is more strict).

A new patch release will follow in a few minutes. Thanks for reporting, it's my fault for not having run the test suite against HHVM after the last few commits :-(

**Comment by nrk** [comment]
Predis v1.0.3 is now available fixing this issue on HHVM.

Thanks for reporting, @keiosweb!

**Comment by keiosweb** [comment]
Yay!
