### ISSUE TITLE
Twemproxy as a Profile

### ISSUE THREAD

**Issue by theUniC** [nrk/predis#271]
Hi,

What do you think about adding twemproxy as a Redis profile on predis? Twemproxy has no support for some commands, so it may make sense to add it as a Redis profile.

Thanks.
Christian.

**Comment by nrk** [comment]
Right now I'd like to change how profiles work starting with Predis v2.0 by not having a huge named array of `$commandID => $commandClass` entries and using a bit of convention-over-configuration for autoloading. It's still a vague and fuzzy idea (I will discuss planned macro-changes for v2.0 on a dedicated issue here on GitHub), but everything considered I'm a bit hesitant to add something that may change in a not-so-distant future at least until I have a clear idea.

That said, I think this could be something that suits well a separate library published on composer.
