### ISSUE TITLE
HashKey Iterator

### ISSUE THREAD

**Issue by guizdiabolik** [nrk/predis#273]
in Predis\Collection\Iterator\HashKey, 

    /**
     * {@inheritdoc}
     */
    protected function extractNext()
    {
        $this->position = key($this->elements);
        $this->current = array_shift($this->elements);
    }

If keys of $this->elements contain numerical values, array_shift re-indexes the array.
So, when we iterate the collection, we lost the original values after the first call of array_shift.

using the same method as Predis\Collection\Iterator\SortedSetKey fix the problem.

    /**
     * {@inheritdoc}
     */
    protected function extractNext()
    {
        if ($kv = each($this->elements)) {
            $this->position = $kv[0];
            $this->current = $kv[1];

            unset($this->elements[$this->position]);
        }
    }

**Comment by itailulu** [comment]
Thanks for the fix.
Any estimation when this fix will be released?

**Comment by nrk** [comment]
Fixed in 1399d38. Patch release v1.0.4 is due in a few days.
