### ISSUE TITLE
Alternative to MULTI/EXEC transaction for aggregate connections?

### ISSUE THREAD

**Issue by eventbase-web** [nrk/predis#275]
I've recently moved from a single instance of redis to a 3.0 redis cluster, and have an application that uses a transaction to ensure that two related key/values are set atomically. 

I see that MULTI/EXEC is not supported for aggregate connections, but it's not clear to me what the alternative is. Could anyone point me in the right direction? Likewise I'm curious to know why they aren't supported, since the redis docs say that transactions on the same shard are supported.

**Comment by eventbase-web** [comment]
Never mind, I figured out that EVAL will accomplish what I need.

**Comment by eventbase-web** [comment]
My apologies, I'm re-opening this because I clearly do not understand what is supported with redis-cluster!

I'm using redis-cluster 3.0 and predis version v1.0.3.

Previously my application used a transaction to ZADD a key to a sorted set and SET to set the key/value.  

Following the example, I created a ScriptCommand:

```php
use Predis\Command\ScriptCommand;

class AddJobLuaScript extends ScriptCommand
{

    /**
     * Gets the body of a Lua script.
     *
     * @return string
     */
    public function getScript()
    {
        /**
         * $tx->zadd($queue_key, $priority, $job_id);
         * $tx->set($job_item_key, $enc_job_item);
         */
        return <<<LUA
local queue_key, priority, job_id = ARGV[1], ARGV[2], ARGV[3]
local job_item_key, enc_job_item = ARGV[4], ARGV[5]

redis.call('zadd', queue_key, priority, job_id)
redis.call('set', job_item_key, enc_job_item)
LUA;

    }
}
```

And in my application I'm calling it like this:

```php
$redis_profile = $this->client->getProfile();
$redis_profile->defineCommand('add_job', 'XomoLibs\Processing\AddJobLuaScript');
$this->client->add_job($queue_key, $priority, $job_id, $job_item_key, $enc_job_item);
```

Which works fine when connecting to a single instance of redis, but when I create a client with multiple servers and run the code, I get the following error:

`(Predis\NotSupportedException) Cannot use 'EVALSHA' with redis-cluster.`

I'm at a bit of a loss as to what to do. The application is a queue: the sorted set is the list of tasks to run, and the value of each task is a serialized object that is deserialized and run. I don't know how else to implement this without using some sort of atomic write.

**Comment by eventbase-web** [comment]
I've realized that by not implementing `getKeysCount()` in the above class, I inadvertently made it impossible for predis to generate a slot. I still don't entirely understand how I'm meant to use KEYS vs ARGV in the Lua script, but at the very least I'm not getting the `NotSupportedException`.

**Comment by nrk** [comment]
From the [redis-cluster docs](http://redis.io/topics/cluster-tutorial#migrating-to-redis-cluster):

> 1. Multiple keys operations, or transactions, or Lua scripts involving multiple keys, are not used. Keys are accessed independently (even if accessed via transactions or Lua scripts grouping multiple commands, about the same key, together).
2. Multiple keys operations, transactions, or Lua scripts involving multiple keys are used but only with keys having the same hash tag, which means that the keys used together all have a {...} sub-string that happens to be identical. For example the following multiple keys operation is defined in the context of the same hash tag: SUNION {user:1000}.foo {user:1000}.bar.
3. Multiple keys operations, transactions, or Lua scripts involving multiple keys are used with key names not having an explicit, or the same, hash tag.

That's why MULTI / EXEC and Lua scripting don't work: all the keys in a command must compute the same hash. Note that `$client->transaction()` won't work anyway (`Predis\NotSupportedException`) because it's limited to single node connections so you should create a new client instance by picking the connection associated to the correct node, but you'll still get a `-CROSSSLOT` error response from redis if one or more keys do not result in the same hash.

**Comment by eventbase-web** [comment]
Thanks for your response. In the mean time I was able to sort out what you already know--that I needed to use hash tags to make sure all the operations were hitting the same node in the cluster.

I'm going to put my updated code here in case it helps anyone in the future who ran into the same issue. What really confused me was the `NotSupportedException` message, because the actual problem with my code was that I was not passing a key and as a result was returning a null slot. I'm sure I could have done a better job understanding the Lua example, but that was not at all obvious to me until I read the Predis code.

Here's my updated script class for posterity:

```php
use Predis\Command\ScriptCommand;

class AddJobLuaScript extends ScriptCommand
{
    /**
     * The value returned is used to determine which of the arguments passed to the script are added to the KEYS array
     *
     * Value is used as a length argument in array_slice, so negative offsets are allowed
     * @see ScriptCommand::getKeys()
     *
     * Keys should use the hash tag format (e.g. {job:queue}:foo, {job:queue}:bar) to ensure that all
     * commands are executed on the same redis instance
     * @see http://redis.io/topics/cluster-tutorial
     *
     * @return int
     */
    public function getKeysCount()
    {
        return 2;
    }

    /**
     * Gets the body of a Lua script.
     *
     * @return string
     */
    public function getScript()
    {
        /**
         * Method signature: add_job(queue_key, job_item_key, priority, job_id, serialized_job_item)
         */
        return <<<LUA
-- get keys for saving queue, job
local queue_key, job_item_key = KEYS[1], KEYS[2]

-- get priority, job id and serialized job
local priority, job_id, serialized_job_item = ARGV[1], ARGV[2], ARGV[3]

-- load insert library and initialize results object
local insert, results = table.insert, {}

-- do redis commands and put the responses into results object
insert(results, 1, redis.call('zadd', queue_key, priority, job_id))
insert(results, 2, redis.call('set', job_item_key, serialized_job_item))

-- return responses from each command
return results
LUA;
    }
}
```

And usage in my app:

```php
            $redis_profile = $this->client->getProfile();
            $redis_profile->defineCommand('add_job', 'Acme\ScriptCommands\AddJobLuaScript');
            $responses = $this->client->add_job($queue_key, $job_item_key, $priority, $job_id, $serialized_job_item);
```

Would you be open to a PR with an Lua example that uses an aggregate connection?
