### ISSUE TITLE
PHP-FPM mode can't suppose unix socket connect ?

### ISSUE THREAD

**Issue by iyaozhen** [nrk/predis#277]
Predis is very good, I already use it in my project. But I have a problem.

This is a demo:
```php
require "frame/predis/Autoloader.php";
Predis\Autoloader::register();
$redis = new Predis\Client([
    'scheme' => 'unix',
    'path' => "/home/work/local/monitor/redis/redis.sock",
]);

$redis->set('test', '123');
echo $redis->get('test')."###\n";
```
cli: 
```
php test.php
123###
```
well done.

But, when I access http://xxx/test.php: 
![image](https://cloud.githubusercontent.com/assets/4395553/9513255/42cf697c-4cc0-11e5-8bce-a07a43e7560f.png)

It connect redis use TCP socket, but I set my redis "port 0", so failure.

I use nginx/1.4.4, php/5.4, redis/3.02, predis/1.0.3 and my system is Red Hat 4.4.4.

**Comment by iyaozhen** [comment]
I modify redis.conf and listen on a TCP socket again, It is work well.

**Comment by nrk** [comment]
Hardly related to Predis. Check the permissions of your UNIX domain socket file to make sure that the user of your PHP processes can properly access it.

**Comment by iyaozhen** [comment]
Thx, I forget check this point.

**Comment by iyaozhen** [comment]
@nrk Maybe not UNIX socket permissions's reason. I chmod 777 redis.socket file, but It is not work.
```
srwxrwxrwx  work work   redis.sock
```

**Comment by nrk** [comment]
@iyaozhen it's not an issue related to Predis anyway or you wouldn't be able to use UNIX sockets via CLI. The exception says your script is trying to connect using TCP sockets which means it's a most likely a misconfiguration of your script.

**Comment by iyaozhen** [comment]
@nrk I understand. I just worry it's Predis's bug. I'll check my environment again, It is must be my bug.

**Comment by allella** [comment]
There is another explanation for CentOS / RHEL 7 and related operating systems using SELinux.

SELinux blocks the connection between PHP-FPM and the unix sockets, even when permissions are 777.

There may be a policy that allows Redis and PHP-FPM to talk. In a pinch, disabling SELinux at /etc/sysconfig/selinux and rebooting allows the socket to immediately work.

If someone finds the proper SELinux policy to allow the two to talk then please post.
