### ISSUE TITLE
Custom Session Handler with predis

### ISSUE THREAD

**Issue by skynet** [nrk/predis#281]
Since it is not possible to setup the native PHP Session handler to write to remote redis master and read from local redis slave (https://github.com/phpredis/phpredis/issues/646), would it be possible to adjust your example (https://github.com/nrk/predis/blob/v1.0/examples/session_handler.php) for such scenario? Thank you.

**Comment by nrk** [comment]
Since `Predis\Session\Handler`'s constructor takes an instance of `Predis\ClientInterface` you can just configure the client to work in a master/slave setup just like in the following example:

```php
$parameters = [
    'tcp://127.0.0.1:6379?alias=master',
    'tcp://127.0.0.1:6380?alias=slave',
];

$client = new Predis\Client($parameters, ['replication' => true, 'prefix' => 'sessions:']);

$handler = new Predis\Session\Handler($client);
$handler->register();
```

I've never tested this but it should work.
