### ISSUE TITLE
Replication and multiple connections - only 1 master allowed?

### ISSUE THREAD

**Issue by urg** [nrk/predis#282]
We're looking into using the replication features, however, we're using several different connections.  The problem we're encountering is that it appears that you can only use 1 master alias.

It looks like the initial idea in https://github.com/nrk/predis/issues/21 had a `?master=1` instead of an `?alias=master`, which would probably solve this issue?  Was there a reason for the alias change?  Any objection to supporting both?

**Comment by nrk** [comment]
You can have only one master when relying on replication anyway, so it's not really clear to me how such a change could make any difference. What do you mean more precisely by _several different connections_?
