### ISSUE TITLE
Include getter for private property `responses` in Predis\Pipeline\Pipeline.php

### ISSUE THREAD

**Issue by khatribharat** [nrk/predis#287]
I wanted to run get commands in a redis pipeline. I changed the source to include a getter for `responses`, and used it after calling `Redis::pipeline`. The following worked for me.
```php
$pipe = null;
Redis::pipeline(function($_pipe) use(&$pipe) {
    $_pipe->hget($key1, $field);
    $_pipe->get($key2);
    $pipe = $_pipe;
}
$responses = $pipe->getResponses();
$res1 = $responses[0];
$res2 = $responses[1];
```

**Comment by nrk** [comment]
I don't know where `Redis::pipeline` comes from and how it handles command pipelines but results from a pipeline should definitely be returned by this function.
