### ISSUE TITLE
Need some limit for unsuccessful connections in SentinelReplication::retryCommandOnFailure

### ISSUE THREAD

**Issue by djagya** [nrk/predis#290]
There is a problem with goto block in `SentinelReplication::retryCommandOnFailure`: if option `autoRetry` equals `true` this goto block will be executed infinitely (and load php and sentinel processes).
We need some limit for unsuccessful connections.
I can create a PR. For now i'm forking the lib with this and my last issue fixed

**Comment by nrk** [comment]
@djagya fixed in eb154cd, 622e6c6 and 0ec9f33. Thanks!
