### ISSUE TITLE
Support database selection with sentinel

### ISSUE THREAD

**Issue by jeremos** [nrk/predis#291]
Hi, 
The database selection doesn't seem to be effective. When we define a sentinel with a string like 'tcp://192.168.0.1:7000/5?timeout=1.0' or an associative array with a database key, all requests are made on the #0 database.
The doc is a little bit obscure about database selection. Did I miss something ?

Thanks for your work
Jeremie

**Comment by nrk** [comment]
@jeremos after commit a816adf you will be able to set default connection parameters for connections created dynamically (e.g. when using redis-sentinel) simply by using the `parameters` option via client options. This is an example of configuration that will use the same database and password for all the connections when using redis-sentinel:

```php
$sentinels = ['tcp://127.0.0.1:5380', 'tcp://127.0.0.1:5381'];

$options = [
    'replication' => 'sentinel',
    'service'     => 'mymaster',
    'parameters'  => ['database' => 2, 'password' => 'MYPASSWORD'],
];

$client = new Predis\Client($sentinels, $options);
```

Thanks for the suggestion!

**Comment by jeremos** [comment]
Hi Daniele
Thanks 
Regards
Jeremie
