### ISSUE TITLE
Redis cluster + Pub/Sub

### ISSUE THREAD

**Issue by m157y** [nrk/predis#293]
Predis blocks Consumer creating on Redis cluster connections with next message:
`Cannot initialize a PUB/SUB consumer over aggregate connections.`

But it supported by Redis cluster, next string is quote from cluster specification:
`The cluster bus is also used in order to propagate Pub/Sub messages across the cluster`
http://redis.io/topics/cluster-spec#clients-and-servers-roles-in-the-redis-cluster-protocol

**Comment by nrk** [comment]
This is unfortunately a limitation of the current design of Predis. It's not possible to use commands such as `SUBSCRIBE` that do not carry a key (which is used internally to calculate the corresponding slot in the cluster against which the command is executed). Furthermore some higher-level abstractions, such as `Predis\PubSub\Consumer`, do not work with aggregate connections. I have plans to solve this in the long run, but I don't have any roadmap as of now.

**Comment by ahfeel** [comment]
:+1: 

My understanding is that we can SUBSCRIBE and PUBLISH to any node of a redis cluster and the messages should flow correctly, so there's no need to compute a slot, no ?

Really needing this :-(

**Comment by m157y** [comment]
@ahfeel I use code below as temporary workaround:
```
$connections = iterator_to_array($predis->getConnection()->getIterator());
$connection = $connections[array_rand($connections)];
```
It returns single connection to random node and it's possible to use SUBSCRIBE/PUBLISH via this connection.

**Comment by ahfeel** [comment]
@m157y Thanks for the tip ! Is it actually correct to make any request to any node (out of the pub/sub scope) ?

**Comment by m157y** [comment]
@ahfeel Yes, PUB/SUB messages will be propogated to all nodes via Cluster Bus. It's described here: http://redis.io/topics/cluster-spec#clients-and-servers-roles-in-the-redis-cluster-protocol

**Comment by ahfeel** [comment]
Thanks for the answer @m157y ;) Actually my question was wider, because I knew that already for the pub/sub, my question is can I send a get or put request to any node and it will forward it properly ? Or this is only valid for pub/sub ?

**Comment by m157y** [comment]
@ahfeel, if you're talking about operations with keys (e.g. set/get), so not, it'll return something like `(error) MOVED 12182 127.0.0.1:6382`. And some actions, like flushdb will work only for specified node. So if you want to flush db (e.g. `flushdb 0`), you'll need to send it to all nodes of the cluster.

**Comment by ahfeel** [comment]
Allright, sounds clear ;) Thanks !

On Thu, Feb 4, 2016 at 2:46 PM, Andrey <notifications@github.com> wrote:

> @ahfeel <https://github.com/ahfeel>, if you're talking about operations
> with keys (e.g. set/get), so not, it'll return something like (error)
> MOVED 12182 127.0.0.1:6382. And some actions, like flushdb will work only
> for specified node. So if you want to flush db (e.g. flushdb 0), you'll
> need to send it to all nodes of the cluster.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nrk/predis/issues/293#issuecomment-179847877>.
>



-- 
Jérémie BORDIER

**Comment by nrk** [comment]
Starting with Predis v2.0 (currently under heavy development), when using redis-cluster it is possible to initialize a PUB/SUB context doing the following:

```php
// Get a client for a random node of the cluster by slot.
$nodeClient = $client->getClientBy('slot', mt_rand(0, 16383));
// Initialize the PUB/SUB context using the client for the retrieved node.
$pubsub = $nodeClient->pubSubLoop(['subscribe' => 'channel:foo']);
```

This creates a client out of a random node in the cluster, but it is possible to target specific nodes using the other variants supported by `Predis\Client::getClientBy()` (e.g. getting a client targeting a specific key).

I'm closing this issue as this solution is generalized enough but I can't exclude that I won't make this mechanism automatic in the client when dealing with redis-cluster, I'll decide later on the development of the next major version as this has a lower priority.

**Comment by Warchiefs** [comment]
@nrk 
How is your progress with Predis v2.0?

**Comment by jrots** [comment]
Given the maturity of redis cluster, any plans of having this supported?

**Comment by renepardon** [comment]
Also have this problem right now. Whats current state of v2? Maybe there is a workaround? 

Within laravel I do it like this:

```php
    public function __construct(RedisManager $manager)
    {
        parent::__construct();

        $this->redis = $manager->connection('pubsub');
    }

// ...
    public function handle() 
    {
        $this->redis->psubscribe('media.*', Closure::fromCallable([MediaChannel::class, 'onVideoMovedToCloudStorage']));
    }
```

But also by retrieving a spcific connection - in my case "pubsub" - doesn't seem to work.

**Comment by DJPretorius** [comment]
@nrk, You said this in 2016.
> Starting with Predis v2.0 (currently under heavy development)

Is it still under development or is the package being abandoned?

**Comment by mfn** [comment]
@DJPretorius see https://github.com/nrk/predis/issues/587 (pinned issue)
