### ISSUE TITLE
Connection refused [tcp://127.0.0.1:6379] But I already set other host and port

### ISSUE THREAD

**Issue by iyaozhen** [nrk/predis#295]
My code:

```PHP
<?php
# predis code:
require "predis/Autoloader.php";
Predis\Autoloader::register();
$redis = new Predis\Client('tcp://10.58.174.11:6479');
$redis->set('foo', 'bar');
echo $redis->get('foo').PHP_EOL;
# phpredis code:
$redis2 = new Redis();
$redis2->connect('10.58.174.11', 6479);
$redis2->set('foo', 'bar2');
echo $redis2->get('foo').PHP_EOL;
```

I run this script in cli:
```
$ php test.php
bar
bar2
```

But when I request url http://xxx.com/test.php return 500

```
[24-Dec-2015 14:06:51 PRC] PHP Fatal error:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'Connection refused [tcp://127.0.0.1:6379]' in /home/work/local/monitor/odp/webroot/servicegraph/api/frame/predis/Connection/AbstractConnection.php:168
Stack trace:
#0 /home/work/local/monitor/odp/webroot/servicegraph/api/frame/predis/Connection/StreamConnection.php(97): Predis\Connection\AbstractConnection->onConnectionError('Connection refu...', 111)
#1 /home/work/local/monitor/odp/webroot/servicegraph/api/frame/predis/Connection/StreamConnection.php(58): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters))
#2 /home/work/local/monitor/odp/webroot/servicegraph/api/frame/predis/Connection/AbstractConnection.php(94): Predis\Connection\StreamConnection->createResource()
#3 /home/work/local/monitor/odp/webroot/servicegraph/api/frame/predis/Connection/StreamConnection.php(158): Predis\Connection\AbstractConnection->connect()
#4 /home/work/local/monitor/odp/webroot/servicegraph/api/frame/predis/Connect in /home/work/local/monitor/odp/webroot/servicegraph/api/frame/predis/Connection/AbstractConnection.php on line 168
```

I del predis code, phpredis code run success, this url return string 'bar2'.

My webserver is Nginx + PHP-FPM. Before this I connect use local unix sock, Now I change local redis to remote server.

I am confused, I already set host[10.58.174.11] and port[6479], why php-cli is OK, but url is failure.

**Comment by tin-cat** [comment]
You've specified the IP 10.58.174.11 in your code, yet the error returned is about trying to connect to the 127.0.0.1 IP, that would be where to start investigating, I guess. Try passing connection parameters to Predis\Client as a hashed array instead of a connection string, like so:

`$redis = new Predis\Client([
    'scheme' => 'tcp',
    'host'   => '10.58.174.11',
    'port'   => 6379,
]);`

Also, you're using a different port for the Redis server (6479) instead of the default (6379), that ok?

**Comment by iyaozhen** [comment]
@tin-cat Thx. I determine, It is 6479. And php-cli is success.
Hashed array config is failure too.

I am tired Last night, make some mistake. Go home sleep, Maybe tomorrow morning It is OK.

**Comment by tin-cat** [comment]
:D happens often, you'll see this a lot clearer tomorrow, have a good night!

**Comment by nrk** [comment]
I doubt this issue is directly related to Predis so I'm closing it, but feel free to re-open it if there are updates.

**Comment by ivanferrer** [comment]
The httpd scripts by default are not allowed to connect out to the network.
This would prevent a hacker from breaking into you httpd server
and attacking other machines. If you need scripts to be able to:

sudo /usr/sbin/setsebool httpd_can_network_connect=1 
sudo  setsebool -P httpd_enable_homedirs 1

**Comment by tangod0wn** [comment]
For all the other people on this page from google,

this is what I needed to do to fix this error,

if you're on a mac install redis with homebrew by running:

$ brew install redis

run the redis server from command line by running:

$ redis-server /usr/local/etc/redis.conf

**Comment by flik** [comment]
Here is solution: https://rapidsol.blogspot.com/2018/10/php-fatal-error-uncaught.html

**Comment by xlcrr** [comment]
I had this error after upgrading AWS instance type. After restarting the server and nginx, it just worked after about 10-15 mins.

**Comment by embtelsolution** [comment]
For Linux users please `sudo apt-get install redis-server` and that's it

**Comment by LinusGeffarth** [comment]
@tangod0wn thanks for the fix. is there a way to have it run in the background? don't want to run that command and keep the terminal window open anytime I need a new access token...

**Comment by zaheerkzz** [comment]
i have working php laravel fine on local machine but when deploy on server it showing following error: Predis \ Connection \ ConnectionException (110)
Connection timed out [tcp://185.151.30.172:6379]
can anyone help, i deployed my code on a sharedhosting

**Comment by melmelc** [comment]
I've facing a problem while connecting to predis server with Fatal Error : Uncaught Predis\Connection\ConnectionException: No connection could be made because the target machine actively refused it [tcp://127.0.0.1:6379] in D:\xampp\htdocs\vendor\predis\predis\src\Connection\AbstractConnection.php:131 Stack trace: #0

I've tried to reinstall composer & predis, turning off windows firewall but the problem still persists. Is there any solution ?
