### ISSUE TITLE
Sort by external key

### ISSUE THREAD

**Issue by abraovic** [nrk/predis#297]
Hi @nrk ,

Can you please help me with sorting by external key (http://redis.io/commands/sort#sorting-by-external-keys)?

I couldn't find any example for this. Is there any way to do this or I need to use rawCommand?

Thanks,
Ante

**Comment by nrk** [comment]
Hi @abraovic,

Pick whichever method you prefer:

```php
$redis->sort("mylist", "by", "weight_*");
$redis->sort("mylist", ["by" => "weight_*"]);
```

**Comment by abraovic** [comment]
Great, thanks.

**Comment by abraovic** [comment]
Hi again,

I have founded all options in code. Here is what you should have (I haven't tested all so please feel free to correct me):

```
$redis->sort(
    "mylist",
    [
        "by" => "weight_*",
        "get" => "object_*",
        "limit" => array($m, $n),
        "sort" => "DESC", // or ASC
        "alpha" => true, // if false it won't take it
        "store" => "resultkey"
    ]
)
```

Hope this saves a bit of time for someone.

Ante.
