### ISSUE TITLE
try catch can not catch the exception

### ISSUE THREAD

**Issue by cnzhangxl** [nrk/predis#301]
2016/01/07 11:17:08 [error] 11624#10436: *1 FastCGI sent in stderr: "PHP Fatal error:  Uncaught exception 'Predis\Connection\ConnectionException' with message '由于目标计算机积极拒绝，无法连接。 [tcp://192.168.50.37:7010]' in D:\web\lib\predis-1.0\src\Connection\AbstractConnection.php:168

**Comment by tPl0ch** [comment]
http://www.reactiongifs.us/wp-content/uploads/2013/09/dont_believe_you_anchorman.gif

**Comment by cnzhangxl** [comment]
i'm sorry

**Comment by GrahamCampbell** [comment]
Did you forget to import the exception?
