### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by cnzhangxl** [nrk/predis#304]
Clusters of concurrent connections to 1000, the cluster timeout, the modification which parameters linux, cluster socket is it enough?

Could not connect to Redis at 10.58.52.60:8303: Connection timed out
tcp_port:8300
connected_clients:13
tcp_port:8302
connected_clients:4
tcp_port:8303
connected_clients:3
tcp_port:8304
connected_clients:9
Could not connect to Redis at 10.58.52.60:8300: Connection timed out
Could not connect to Redis at 10.58.52.60:8301: Connection timed out
tcp_port:8301
connected_clients:9
tcp_port:8302
connected_clients:8
Could not connect to Redis at 10.58.52.60:8304: Connection timed out
tcp_port:8300
connected_clients:8

**Comment by nrk** [comment]
I'm not exactly sure I understand what your question is, can you clarify please?

**Comment by nrk** [comment]
Closing due to lack of feedback, but feel free to add more details and I'll eventually reopen this issue if it's indeed something directly related to the client.
