### ISSUE TITLE
PHP7: Blows up with over-memory usage.

### ISSUE THREAD

**Issue by IngwiePhoenix** [nrk/predis#305]
```
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ npm run shell

> BIRD3@3.0.0-dev.76 shell /Users/Ingwie/Work/BIRD3
> util/artisan tinker

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /Users/Ingwie/Work/BIRD3/php_modules/predis/predis/lib/Predis/Connection/AbstractConnection.php on line 141

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /Users/Ingwie/Work/BIRD3/php_modules/predis/predis/lib/Predis/Connection/AbstractConnection.php on line 141
```

I dont know if this is my code, or yours... Could oyu investigate?

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/BIRD3 $ php --version
PHP 7.0.2 (cli) (built: Jan 25 2016 23:51:44) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by GrahamCampbell** [comment]
I can't replicate?

**Comment by IngwiePhoenix** [comment]
Turns out my Redis was not running. I had installed it, but forgotten to kick it up.

Might want to see if Redis is running at all before trying to connect to it...?

**Comment by nrk** [comment]
@IngwiePhoenix if you don't report which version of Predis you are currently using I can't even start investigating, line 141 in AbstractConnection.php points to a comment in recent stable versions of Predis. If you always want to connect to redis and catch the exception if the operation fails then just use `$client->connect()` before anything else.

That said, it seems more like a memory leak in PHP7 than a bug in Predis to me.

**Comment by cebe** [comment]
such an error may also occur on infinite recursive call. can you show the error stack trace?

**Comment by nrk** [comment]
Closing due to lack of feedback and inability to reproduce this issue.

**Comment by cruelbob** [comment]
Reproduced in docker-for-mac enviroment both on alpine and debian images on all versions of php-fpm on last version of predis calling rpush without running redis.

**Comment by cebe** [comment]
can you show the error stack trace?

**Comment by cruelbob** [comment]
There is no stacktrace. It doesn't crash immediately but after some time after call to rpush.

**Comment by cebe** [comment]
There is always a stacktrace, it may just not be shown. Using a custom error handler can help to make it visible. If you are not able to get the stack trace, could you provide some code to reproduce it?

**Comment by cruelbob** [comment]
Found bug in my code. Thanks.
