### ISSUE TITLE
PHP7 compatibility please!

### ISSUE THREAD

**Issue by jonathanpmartins** [nrk/predis#308]
As fas I know this is the only way to comunicate php7 with redis today! https://laracasts.com/discuss/channels/tips/tutorial-guide-installing-php-redis-on-fresh-install-homestead-with-php7

Is there another way?

**Comment by nrk** [comment]
This is not an issue and it's unrelated to Predis (it works perfectly fine with PHP 7).

**Comment by jonathanpmartins** [comment]
@nrk

When I use it with Lumen 5.2, PHP 7.0.2 "Redis Facade", it keep throwing a error in my tests. Like So:

In my composer.json file

    "illuminate/redis":"5.2.*",
    "predis/predis": "^1.1@dev"

In my bootstrap/app.php file

	$app->register(Illuminate\Redis\RedisServiceProvider::class);

In my test file

```php
<?php

use Illuminate\Support\Facades\Redis;

class RedisWithFacade extends TestCase
{
    public function simpleTest()
    {
        $key = 'test';
        $value = 'tested';
        try {
            Redis::put($key, $value);
            $redisRow = Redis::get($key);

            $this->assertEquals($redisRow, $value);

            if ($redisRow == $value) {
                Redis::del($key);

                $redisDel = Redis::get($key);

                dd($redisDel);
            }
        } catch (Exception $e) {
            $exception = [
                'message' => $e->getMessage(),
                'code' => $e->getCode(),
                'file' => $e->getFile(),
                'line' => $e->getLine()
            ];
            dd($exception);
        }
    }
}
```

It thows a Exeption:

	{
	  ["message"]=>
	  string(48) "Command 'PUT' is not a registered Redis command."
	  ["code"]=>
	  int(0)
	  ["file"]=>
	  string(78) "vendor/predis/predis/src/Profile/RedisProfile.php"
	  ["line"]=>
	  int(88)
	}

When I install everything in the server I use the ondrej/phprepository. You can look-up the setup installation script here: https://github.com/jonathanpmartins/ubuntusetup/blob/master/server/setup-php7-nginx-1.9.10-ubuntu-14.04.sh

Perhaps I should do something different to everything work. Can you help me out?
Thanks for your time!

**Comment by nrk** [comment]
`PUT` is not a Redis command, it's [`SET`](redis.io/commands/set). As for the rest, as I've said, it's unrelated to Predis (and I don't even use Laravel so I don't know how to deal with it).

**Comment by jonathanpmartins** [comment]
Thanks, so far you answer me a question. :+1: 
I take a deep look into the new Lumen code.
Again, thanks for your time!
