### ISSUE TITLE
SetNx with TTL?

### ISSUE THREAD

**Issue by loostro** [nrk/predis#309]
Is it possible to have SetNX with TTL time?

**Comment by cheprasov** [comment]
Please, use __SET__ command.
`SET key value [EX seconds] [PX milliseconds] [NX|XX]`
Example: `SET foo bar EX 60 NX`

**Comment by cheprasov** [comment]
Oops... I thought it was a question about Redis, instead Predis.

**Comment by nrk** [comment]
@loostro just use `SET` as pointed by @cheprasov, `SETNX` does not support having a TTL in Redis (see the docs on http://redis.io).

**Comment by profbiss** [comment]
SET command not working
set('xxxxx', 1, 'EX 10', 'PX 10000', 'NX')


Dump $buffer in writeRequest function in StreamConnection.php
`*6
$3
SET
$5
xxxxx
$1
1
$5
EX 10
$8
PX 10000
$2
NX
`


On cli work:

`127.0.0.1:6379> SET xxxxx 1 EX 10 PX 10000 NX`
`OK`

**Comment by nrk** [comment]
@profbiss there's no issue, you are simply doing it wrong: it's `$client->set('xxxxx', 1, 'EX', '10', 'PX', '10000', 'NX')`.

**Comment by profbiss** [comment]
@nrk tnx worked

Pls fix phpdoc in ClientInterfhace.php
Not work - `* @method mixed  set($key, $value, $expireResolution = null, $expireTTL = null, $flag = null)`
Work - `* @method mixed  set($key, $value, $EX, $exSecs = null, $PX, $psMsecs = null, $flag = null)`
