### ISSUE TITLE
Need to Support Connections via SSL

### ISSUE THREAD

**Issue by timnolte** [nrk/predis#310]
We use Redis with the only access being SSL, stunnel is receiving the outside connections and passing to a non-SSL localhost connection. We have been happily using a custom phpredis build that supports SSL for our PHP sessions. We are moving development to new Laravel backend services and need SSL support built-in so we don't have to additionally install stunnel on the web servers. Also, our Redis instance access goes through an HAProxy load balancer. SSL is fast becoming the new norm so this should be on the roadmap to support.

https://github.com/bbroerman30/ssl-phpredis

**Comment by nrk** [comment]
SSL will be supported starting from Predis v1.1 and it's already implemented in the master branch, unfortunately it cannot be backported to v1.0 as it would introduce some breaking changes.
