### ISSUE TITLE
Support for timeouts in pubsub using stream_select

### ISSUE THREAD

**Issue by SamMousa** [nrk/predis#313]
Currently when using long running PHP scripts the common method is to set `read_write_timeout` to `0`. For processes running via PHP-FPM this is a problem; since the call to `fread()` blocks indefinitely, the process will not die even if the browser has long since abandoned the connection.

Using a lower timeout and catching the exception is no solution since after the first exception new reads will block indefinitely regardless of messages being send.

I propose a solution that uses `stream_select()` calls with a limited timeout, allowing the PHP script to execute other code in between waiting.

Currently I think this can be realized as follows:
````
$loop = $client->pubSubLoop()
while(true) {
    $streams = [$client->getConnection()->getResource()];
    if (stream_select($streams, null, null, 5) > 0) {
        customMessageHandlerHere($loop->current());
    }
    // Do some other stuff, for example send output so PHP detects if the browser aborted the connection.
    echo '.'; 
    flush();
}
````

This would block for at most 5 seconds before returning control to the calling script, which can do stuff.

It would be ideal to have something like this available besides the `\Iterator` implementation with `read_write_timeout` for waiting for messages.

**Comment by nrk** [comment]
I don't think Redis PubSub is suited for being used in scripts executed by processes running via PHP-FPM, it doesn't make sense to me honestly. `Predis\PubSub\Consumer` is indeed not intended for such scenarios but a different implementation would not be any better.
