### ISSUE TITLE
predis + phpiredis cluster

### ISSUE THREAD

**Issue by diegotez** [nrk/predis#318]
Hello,
I'm trying to use redis clusters with predis + phpiredis as I saw that phpiredis improves the performance.

This is my PHP code:
 ```
$cluster = [
    'tcp://127.0.0.1:30001',
    'tcp://127.0.0.1:30002',
    'tcp://127.0.0.1:30003',
    'tcp://127.0.0.1:30004',
    'tcp://127.0.0.1:30005',
    'tcp://127.0.0.1:30006',
];  

$client = new Predis\Client($cluster,
    [
    'connections' => [
        'tcp'  => 'Predis\Connection\PhpiredisStreamConnection'
    ],
    ]
);
```
I get the following error:

    Fatal error: Uncaught exception 'Predis\Response\ServerException' with message 'MOVED 6918 127.0.0.1:30002' in /var/www/html/predis-1.0/src/Client.php:365 Stack trace: #0 /var/www/html/predis-1.0/src/Client.php(330): Predis\Client->onErrorResponse(Object(Predis\Command\StringGet), Object(Predis\Response\Error)) #1 /var/www/html/predis-1.0/src/Client.php(310): Predis\Client->executeCommand(Object(Predis\Command\StringGet)) #2 /var/www/html/redisTests/predis.php(52): Predis\Client->__call('get', Array) #3 /var/www/html/redisTests/predis.php(52): Predis\Client->get('test') #4 {main} thrown in /var/www/html/predis-1.0/src/Client.php on line 365

Now if i set only the first 2 clusters ips, it works fine. Can someone please explain why?

Can someone tell me what's wrong? Does predis + phpiredis fully support clustering?

Thanks in advance for your help!

**Comment by beberlei** [comment]
It seems clustering is not supported here, this is not an error that should fail, the node just makes a redirect, like a http 301 to the node that has the key you are accessing. Internally Phpiredis should detect this and make a new request to the correct node.

**Comment by nrk** [comment]
@diegotez you are missing a vital client option that instructs Predis to operate in a redis-cluster environment. As [pointed in the README](https://github.com/nrk/predis#cluster), in your specific case the client should be initialized like this:

```php
$client = new Predis\Client($cluster, [
    'cluster' => 'redis',
    'connections' => [
        'tcp'  => 'Predis\Connection\PhpiredisStreamConnection'
    ],
]);
```
