### ISSUE TITLE
Using predis with PHP code deployed in Apache2

### ISSUE THREAD

**Issue by yahavb** [nrk/predis#319]
Hello - I am trying to use predis for php code deployed on Apache2 that runs in Ubuntu 15.
Can you please guys help me understand how to compile and deploy the client library in the apache. 
Is it new Apache module or a more general shared object?

Thank you!

**Comment by cebe** [comment]
predis is pure PHP, there is nothing to compile... See the readme for more details: https://github.com/nrk/predis#how-to-use-predis

**Comment by yahavb** [comment]
Thanks! I might miss something here.
Here are my steps:
1. installed composer https://getcomposer.org/download/

2. I created composer.json
{
	"require": {
		     “predis/predis”: ">=1.0.3”
		       }
}  

when I try to execute a code with predis e.g.
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
require 'Predis/Autoloader.php';
Predis\Autoloader::register();
if (isset($_GET['cmd']) === true) {
....
It fails and generates the following 
PHP Fatal error:  require(): Failed opening required 'Predis/Autoloader.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/carmel/test.php on line 4

How do I add Predis so it can be loaded by my test php program?

Thank you!

**Comment by cebe** [comment]
1. you need to run `composer install` to install the library.
2. you then need to inlcude the composer autoloader instead of ` require 'Predis/Autoloader.php';` to make it work. https://getcomposer.org/doc/01-basic-usage.md#autoloading

**Comment by yahavb** [comment]
Just tried and it works. Thank you!
