### ISSUE TITLE
array

### ISSUE THREAD

**Issue by Daftpasteur** [nrk/predis#324]
How create an array in redis with predis ?

**Comment by nrk** [comment]
Don't really get your question but if you need to store values in an array-like structure (with numerical indices) in Redis then you need lists (see [list-related commands](http://redis.io/commands#list)), on the other hand if you need a dictionary-like structure (named arrays in PHP) then you need hashes (see [hash-related commands](http://redis.io/commands#hash)). Note that this is just a rough approximation.
