### ISSUE TITLE
How to set cyrilic key?

### ISSUE THREAD

**Issue by mnvx** [nrk/predis#328]
I trying to execute next command.

    Redis::hincrby('sentiment_combined:positive', 'рыжий кот', 1);

This command works perfectly for latin keys, for example `'orange cat'`. But with `'рыжий кот'` I have next error:

    [Predis\Response\ServerException]         
    ERR Protocol error: expected '$', got '�'  <

I has added log into Predis `Predis\Connection\StreamConnection::write()`

    print_r($buffer);echo "---$written---\n";

And I observe output in console:

    *2
    $6
    SELECT
    $1
    0
    ---23---
    *4
    $7
    HINCRBY
    $27
    sentiment_combined:positive
    $9
    рыжий кот
    $1
    1
    ---81---

Redis supporting [any keys][1]. How to overcome this limitation in Predis?

This question [on stackoverflow][2]

  [1]: http://stackoverflow.com/a/30271837/1920758
  [2]: http://stackoverflow.com/questions/36887168/predis-how-to-set-cyrilic-key

**Comment by nrk** [comment]
Predis treats strings as binary blobs so it doesn't care about the underlying string encoding, but there's a certain setting in php.ini that can definitely break this behaviour (see #283 and [mbstring.func_overload](http://php.net/manual/en/mbstring.overload.php)). Please verify if this is the case.

**Comment by mnvx** [comment]
Thanks for response. I have `mbstring.func_overload = 6` for both php-cli and apache. Any idea?

**Comment by cebe** [comment]
make sure no other code needs this setting and set it to 0.

**Comment by nrk** [comment]
The only sane idea in general would be not to use and/ore rely on `mbstring.func_overload` at all and be explicit by using the equivalent `mb_`-prefixed string functions when you need to manipulate multibyte strings. Obviously you must check first and make sure that setting `mbstring.func_overload` to `0` doesn't break any other part of your application.

**Comment by cebe** [comment]
If you'd want to make predis compatible with environments where this setting is set, you could write a strlen wrapper: `function_exists('mb_strlen') ? mb_strlen($s, '8bit') : strlen($s)`

**Comment by nrk** [comment]
@cebe I'm not a fan of the additional overhead (the presence of any `mb_`-prefixed function doesn't automatically mean that the standard PHP string functions are being overloaded after all) for what's actually a corner case and even a bad one at that, because `mbstring.func_overload` is evil.

**Comment by mnvx** [comment]
Thanks, it works with `mbstring.func_overload = 0`, but my project using `6`. And I decided to use transliterations as keys.

**Comment by cebe** [comment]
@nrk I know that it's evil but I did it in most of my libraries for maximum compatibility. If you don't like to do it I'm fine with it, just wanted to point out the option.

**Comment by nrk** [comment]
@cebe yeah I know, I just wanted to clarify the reason why I'd prefer to avoid dealing with `mbstring.func_overload` in Predis :)
