### ISSUE TITLE
HashKey Iterator bug?

### ISSUE THREAD

**Issue by KiberMath** [nrk/predis#331]
i'm doing this 

```
foreach (new \Predis\Collection\Iterator\HashKey($redis, $key) as $user => $value) {
     echo ($user.' => '.$value.PHP_EOL);
}
```

output of it is 

2473490 => 1
0 => 1
0 => 1
0 => 3
0 => 1

when $key has this:
 1) "2473490"
 2) "1"
 3) "14"
 4) "1"
 5) "15"
 6) "1"
 7) "1234"
 8) "3"
 9) "1232"
10) "1"

What happend with $user? why it always zerro?
predis 1.0.3

**Comment by nrk** [comment]
Indeed a bug that got fixed with commit 1399d38. Patch release v1.0.4 is due in a few days.
