### ISSUE TITLE
[2.0] Drop support for PHP 5.3

### ISSUE THREAD

**Issue by nrk** [nrk/predis#335]
Now that (as of writing) the release of v1.1.0 is just matter of a few days and that with this new version Predis basically supports everything needed, I'm starting to play with some changes and ideas for v2.0 that would really benefit from bumping the major required version of PHP thus **dropping support for PHP 5.3**. My plan is to **switch to PHP 5.5** as the minimum required version of PHP which is already the same requirement of big and widespread fameworks such as Symfony (3.0) and Laravel (5.1), making it a sane choice I think. This would help removing some annoying stuff from the code base here simply because of PHP 5.3 and actually improve other parts (e.g. having traits would be great with command classes).

In the end I'm **strongly** biased toward going forward and forget about PHP 5.3 but I'd really love to hear what developers using Predis think about such a major decision. Keep in mind that with 2.0 I also plan to introduce some major breaking changes in the API anyway (aside from what concerns Redis commands as they will still take the same arguments and return the same values) but at the same time there are no plans for any new major feature related to Redis (there's nothing new in this respect) so I guess this is the ideal moment for such a change, and v1.x will still serve well for those that really need to stay on PHP 5.3 or 5.4 especially considered that I plan to maintain Predis v1.x for a while for bug fixes and eventual new minor features.

Your thoughs?

**Comment by GrahamCampbell** [comment]
:+1: Switching to 5.5.9 would be good. That's what symfony have done, and Laravel 5.1 LTS too. It discourages people from using really old 5.5.x versions, and 5.5.9 is what shipped with ubuntu 14.04 LTS too. 16.06 LTS as 7.0.4, or something.

**Comment by GrahamCampbell** [comment]
> Symfony (3.0) and Laravel (5.1), making it a sane choice I think

Ah, you said. :)

**Comment by GrahamCampbell** [comment]
Laravel 5.3 is actually PHP 5.6.4 or higher now btw. ;)

**Comment by nrk** [comment]
@GrahamCampbell I considered PHP 5.6 but I guess it'd be too much of a version bump especially since I can't find any compelling reasons for it. I mean, variadic functions and arguments unpacking are indeed very nice additions to the language to have but I guess I can live without using them in Predis for the sake of a broader diffusion. Thanks!

**Comment by elazar** [comment]
FWIW, 5.5 will be EOL on July 10, 2016 ([source](http://php.net/supported-versions.php)). That said, I know Ubuntu 12.04, which currently has an EOL of April 2017 ([source](https://wiki.ubuntu.com/Releases)), is using 5.5.9, so I'm inclined to agree that discontinuing 5.5 support may be premature.

**Comment by GrahamCampbell** [comment]
> so I'm inclined to agree that discontinuing 5.5 support may be premature.

Though, it'll not be discontinued, because 1.x will still be getting fixes.

**Comment by elazar** [comment]
@GrahamCampbell Ah, fair point. If 1.x will be maintained, then deprecating 5.5 support for 2.0 may be prudent.

**Comment by nrk** [comment]
@elazar all things considered I think that having 5.5.9 as the minimum requirement for 2.0 is the best compromise at the moment. 1.x is going to be maintained on a best-effort basis (just bug fixes and no new features unless they are small things or new commands added in the next couple of minor releases of Redis), but I'd still like to have as much devs as possible upgrade to 2.0 wherever possible because I think the next major version will have some good real improvements (and fewer humongous named arrays allocated upon initialization) and that's why I'd keep one step back from 5.6. Also, Symfony 3.0.

**Comment by GrahamCampbell** [comment]
> all things considered I think that having 5.5.9 as the minimum requirement for 2.0 is the best 

I'd agree with that. :+1: for 5.5.9

**Comment by nrk** [comment]
While we are at this, just testing the waters right now, how about dropping PEAR? You know I would have loved to drop it for `v1.0` but there was a discussion about that on #179 back then, cc @remicollet? To make it worse, by now I only have one VM where building the PEAR packages doesn't return the dreadful error `PEAR_Packagefile_v2::toTgz(): adding package.xml failed` :disappointed:

**Comment by GrahamCampbell** [comment]
> how about dropping PEAR?

YES. KILL IT WITH FIRE. :trollface:

**Comment by nrk** [comment]
@GrahamCampbell that was quick, but also kind of predicable coming from you :wink:

**Comment by GrahamCampbell** [comment]
> that was quick, but also kind of predicable coming from you

Lol, yeh. :P

**Comment by remicollet** [comment]
Dropping 5.3 and pear support seems ok for v2

**Comment by nrk** [comment]
@remicollet thanks, anyway before reaching a decision I'll try setting up the needed environment to build PEAR packages on a new VM I'm preparing right now and automate the process via webhooks whenever I tag a new release on GitHub, if I won't be able to get it working I'll drop PEAR and properly publicize the decision because right now having to do that manually definitely hurts my will of pushing patch releases more frequently.

**Comment by khaperets** [comment]
Very good solution! Because now is most developers (advanced developers) use PHP 7.

**Comment by GrahamCampbell** [comment]
> Because now is most developers (advanced developers) use PHP 7.

Well, or at least 5.6. I of people with large application that can't get onto 7.x yet. 5.5.9 is a perfect new minimum for the 2016 PHP community.

**Comment by nrk** [comment]
> 5.5.9 is a perfect new minimum for the __2016__ PHP community.

Indeed, now the question is which year will see the release of v2.0 :smiley: All jokes aside, I already have a lot of changes and ideas in mind and there's nothing new to be implemented in terms of missing features (the last one was redis-sentinel) so I wouldn't be surprised to have it ready in ~6 months.

**Comment by Seldaek** [comment]
I'd vote for requiring php7 (it's what I did for monolog 2.0, and surprisingly nobody complained :p). If you maintain 1.1 for a while it's fine I think, the lib is pretty stable anyway.

**Comment by nrk** [comment]
@Seldaek I have the feeling that most of the new features implemented in PHP 5.6 and PHP 7.0, despite being nice and all, are not indispensable to improve the library. At the same time, and if everything goes as planned, the next major version of Predis should have less impact in loading times and many developers could benefit from it. This basically means that if it's just for the sake of bumping the requirement to PHP 7.0, I'm not for it.

**Comment by Seldaek** [comment]
Fair enough, I just wanted to bump it to get the strict mode and scalar hints and gently nudge people towards php7 too, but up to you :)

**Comment by GrahamCampbell** [comment]
https://github.com/nrk/predis/pull/347 :P

**Comment by GrahamCampbell** [comment]
Maybe 3.x can be PHP 7 only, in a few years?

**Comment by nrk** [comment]
@GrahamCampbell 

> https://github.com/nrk/predis/pull/347 :P

Is this some kind of subtle pressure? ;P

> Maybe 3.x can be PHP 7 only, in a few years?

Not sure about that, I mean 3.x may see the light when PHP 7.0 will be the new PHP 5.2.

**Comment by nrk** [comment]
Just linking @Seldaek's [PHP Versions Stats - 2016.1 Edition](https://seld.be/notes/php-versions-stats-2016-1-edition) for reference.

**Comment by GrahamCampbell** [comment]
> Is this some kind of subtle pressure? ;P

:trollface:

**Comment by vingrad** [comment]
Does this library support PHP7?

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by lulco** [comment]
What about this: http://php.net/supported-versions.php Support your package just for supported PHP versions.

**Comment by nrk** [comment]
Alright folks, as you might have noticed almost 9 months have passed since this issue was opened and there's still no sign for an imminent release of a major version of Predis (started commiting many BCs to the `master` branch a few months ago but then busy life kicked in 😢). At this point, considering how many more months will be needed at the current pace, I guess we could just aim for PHP 7.0 as the minimum required version and take advantage of it. We'll see as soon as I start working again on Predis if it's feasible or not in practical terms but I'm feeling good about it.

**Comment by nrk** [comment]
I'm very much tempted to commit the following change in the master branch (Predis 2.0) in a short while (few days at max), how would you feel about it? :smile: 

```diff
diff --git a/composer.json b/composer.json
index 505ed00..d17b2ab 100644
--- a/composer.json
+++ b/composer.json
@@ -16,7 +16,7 @@
         }
     ],
     "require": {
-        "php": ">=5.3.9"
+        "php": ">=7.0"
     },
     "require-dev": {
         "phpunit/phpunit": "~4.8"
```

**Comment by nrk** [comment]
Closing this issues as it's being superseded by #620.
