### ISSUE TITLE
Benchmark tools for Predis

### ISSUE THREAD

**Issue by lulyon** [nrk/predis#341]
I've noticed that redis clients from a bunch of other language provide with Benchmark tools (C client Hiredis: redis-benchmark; Java client Jedis: package redis.clients.jedis.tests.benchmark). So, shall we  build Benchmark tools for Predis?

**Comment by nrk** [comment]
@lulyon what a benchmark should represent here, how fast the client is? But what does it mean being fast anyway? How many GET/sec is it able to generate against a Redis instance running on the localhost? That's kind of pointless and we even have a [chapter on the FAQ](https://github.com/nrk/predis/blob/0e17edbefb50c6cbd1acc4a6f6ef06399deb1af2/FAQ.md#speaking-about-performances), performances should be measured in the context of a specific domain and application. If you on the other hand want to see how Redis performs, [`redis-benchmark`](https://github.com/antirez/redis/blob/30c1a8570bbced4f21e0ba59146694fa006b83c0/src/redis-benchmark.c) is already out there and built when compiling Redis itself, it's fairly configurable and optimized.

**Comment by lulyon** [comment]
@nrk There are more features beyond the simple GET/SET operation. Just want to know to what extend overhead predis features bring to access redis, in this case benchmark upon predis should help.

**Comment by dmitry-php** [comment]
Hi all! Maybe @lulyon mean that predis need contain some script like redis-benchmark tool

**Comment by nrk** [comment]
@lulyon that's exactly why I don't want to add something like that in the repository: there are just too many variables to be considered to have a proper benchmark that makes sense, and I don't want to maintain something I'm not interested in.
