### ISSUE TITLE
Call to a member function connect() on null when Sentinel reports no slaves

### ISSUE THREAD

**Issue by samwaters** [nrk/predis#342]
If a sentinel instance reports no slaves on master, connect() fails in `SentinelReplication.php:623` with `Call to a member function connect() on null` since there is no current connection.

In this case, should connect() check for `$this->current` being null and switch `$this->current` to master before trying to call connect(), or handle it with an exception?

**Comment by nrk** [comment]
That was indeed not the correct behavior, fixed it jut now by falling back to the master instance when this happens. By the way redis-sentinel should always report one master server so I didn't add any check for a potential missing master, but I'll check this later to make sure.
