### ISSUE TITLE
Error when new client in for loop using Predis with Phpiredis extension

### ISSUE THREAD

**Issue by lulyon** [nrk/predis#345]
When using `PhpiredisStreamConnection`, it throws error info. 
But when `$options` is set to null,Or call `$client->quit();` in the for loop,  the output is ok. I guess a `__destruct` function (to release connection resource) added to the Class `Client` would help. May I submit a pull request here?

Code:

```
$parameters = array('host' => '127.0.0.1', 'port' => 6379, 'database' => 15, );
$options = array('connections' => array(
        'tcp'  => 'Predis\Connection\PhpiredisStreamConnection',  // PHP stream resources
        'unix' => 'Predis\Connection\PhpiredisSocketConnection',  // ext-socket resources
    ), );

$nquery = 10000;

for($i=0; $i < $nquery; $i++) {
	$client = new Predis\Client($parameters, $options);
	$response = $client->get('library');
	//$client->quit();
}

```

 Output: 
> PHP Warning:  require(/media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/CommunicationException.php): failed to open stream: Too many open files in /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Autoloader.php on line 58
> PHP Stack trace:
> PHP   1. {main}() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/examples/test_benchmark.php:0
> PHP   2. Predis\Client->get() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/examples/test_benchmark.php:25
> PHP   3. Predis\Client->__call() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/examples/test_benchmark.php:25
> PHP   4. Predis\Client->executeCommand() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Client.php:315
> PHP   5. Predis\Connection\AbstractConnection->executeCommand() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Client.php:331
> PHP   6. Predis\Connection\PhpiredisStreamConnection->writeRequest() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/AbstractConnection.php:110
> PHP   7. Predis\Connection\StreamConnection->write() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/PhpiredisStreamConnection.php:215
> PHP   8. Predis\Connection\AbstractConnection->getResource() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/StreamConnection.php:288
> PHP   9. Predis\Connection\StreamConnection->connect() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/AbstractConnection.php:180
> PHP  10. Predis\Connection\AbstractConnection->connect() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/StreamConnection.php:258
> PHP  11. Predis\Connection\StreamConnection->createResource() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/AbstractConnection.php:81
> PHP  12. Predis\Connection\StreamConnection->tcpStreamInitializer() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/StreamConnection.php:100
> PHP  13. Predis\Connection\PhpiredisStreamConnection->createStreamSocket() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/StreamConnection.php:178
> PHP  14. Predis\Connection\AbstractConnection->onConnectionError() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/PhpiredisStreamConnection.php:106
> PHP  15. spl_autoload_call() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/PhpiredisStreamConnection.php:154
> PHP  16. Predis\Autoloader->autoload() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/PhpiredisStreamConnection.php:0
> PHP Fatal error:  require(): Failed opening required '/media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/CommunicationException.php' (include_path='.:/usr/share/php:/usr/share/pear') in /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Autoloader.php on line 58
> PHP Stack trace:
> PHP   1. {main}() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/examples/test_benchmark.php:0
> PHP   2. Predis\Client->get() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/examples/test_benchmark.php:25
> PHP   3. Predis\Client->__call() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/examples/test_benchmark.php:25
> PHP   4. Predis\Client->executeCommand() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Client.php:315
> PHP   5. Predis\Connection\AbstractConnection->executeCommand() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Client.php:331
> PHP   6. Predis\Connection\PhpiredisStreamConnection->writeRequest() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/AbstractConnection.php:110
> PHP   7. Predis\Connection\StreamConnection->write() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/PhpiredisStreamConnection.php:215
> PHP   8. Predis\Connection\AbstractConnection->getResource() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/StreamConnection.php:288
> PHP   9. Predis\Connection\StreamConnection->connect() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/AbstractConnection.php:180
> PHP  10. Predis\Connection\AbstractConnection->connect() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/StreamConnection.php:258
> PHP  11. Predis\Connection\StreamConnection->createResource() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/AbstractConnection.php:81
> PHP  12. Predis\Connection\StreamConnection->tcpStreamInitializer() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/StreamConnection.php:100
> PHP  13. Predis\Connection\PhpiredisStreamConnection->createStreamSocket() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/StreamConnection.php:178
> PHP  14. Predis\Connection\AbstractConnection->onConnectionError() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/PhpiredisStreamConnection.php:106
> PHP  15. spl_autoload_call() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/PhpiredisStreamConnection.php:154
> PHP  16. Predis\Autoloader->autoload() /media/sf_theddrive/wubaProject/wredis/wredis-client/wredis-client-php/predis-1.1-sentinel/src/Connection/PhpiredisStreamConnection.php:0
>

**Comment by GrahamCampbell** [comment]
> Too many open files

This doesn't look like a bug here. Are you using phpdbg? That could be casusing that.

**Comment by lulyon** [comment]
@GrahamCampbell  No, I didn't use phpdbg. `Too many open files` seem to be caused by Predis Client open connections by `PhpiredisStreamConnection` but do not release, in which case, it is a bug.

**Comment by nrk** [comment]
@lulyon there's already a destructor for `Predis\Connection\PhpiredisStreamConnection` that invokes `disconnect()`, it's the one inherited from `Predis\Connection\StreamConnection`).

That said, there's indeed an issue: `Predis\Connection\PhpiredisStreamConnection::__destruct()` is not invoked at all by PHP! After a couple of experiments it seems to be related to the reader callbacks used by phpiredis and I believe it's a refcount issue, if I comment [these two lines](https://github.com/nrk/predis/blob/v1.1.0/src/Connection/PhpiredisStreamConnection.php#L140-L141) the destructor is properly invoked which means there's something keeping the instance alive and preventing the GC to collect it.

I'll look into this, thanks for reporting.

**Comment by nrk** [comment]
Fun fact: everything works perfectly fine with PHP 5.3 but something changed starting with PHP 5.4 (maybe this is related to the fact that closures are automatically bound to `$this` starting with PHP 5.4?). In addition to that, if I replace the closures for the reader callbacks with classes implementing `__invoke()` then everything works as expected. I'm still not sure if it's a bug in phpiredis or I am just missing something.

**Comment by nrk** [comment]
If I change [getStatusHandler()](https://github.com/nrk/predis/blob/v1.1.0/src/Connection/PhpiredisStreamConnection.php#L163-L165) to add the `use` directive in the closure so that it captures `$this` (and do the same for `getErrorHandler()`):

```
protected function getStatusHandler()
{
    $that = $this;

    return function ($payload) use ($that) {
        return StatusResponse::get($payload);
    };
}
```

Then the issue magically presents itself even on PHP 5.3 so I guess my gut feeling was right and the source of the problem is that the connection instance and the closures stored in the reader resource keep each other alive.

I actually have a fix but want to test it a bit.

**Comment by GrahamCampbell** [comment]
Hmmm, PHP is so quirky.

**Comment by nrk** [comment]
@GrahamCampbell heh I'm used to these kind of quirks from back when I was contributing code and code reviews to `reactphp/event-loop` :-)

**Comment by nrk** [comment]
Should be fixed now, @lulyon could you please test to confirm that everything is fine on your end too?

**Comment by lulyon** [comment]
Well done! I've tested the patch and I confirm that everything is fine now.

**Comment by nrk** [comment]
Thanks @lulyon :+1:
