### ISSUE TITLE
Is nrk's PEAR channel broken?

### ISSUE THREAD

**Issue by idiodabble** [nrk/predis#349]
Over the past year, I've had no difficulty in running "pear channel-discover pear.nrk.io" and then "pear install nrk/predis" to install predis, but now I'm receiving "No releases available for package "pear.nrk.io/predis"" and the install fails, and when I run "pear remote-list -c nrk" I get:

File http://pear.nrk.io:80/rest/c/categories.xml not valid (received: HTTP/1.1 404 Not Found)

**Comment by nrk** [comment]
Thanks for reporting, should be fixed now. Could you try again just to make sure? Yesterday I moved the PEAR channel to a new VM but apparently I screwed up something while migrating the files and setting some ACL permissions.

**Comment by idiodabble** [comment]
It works now, thank you!!!
