### ISSUE TITLE
Error with phpunit on SentinelReplicationTest

### ISSUE THREAD

**Issue by lulyon** [nrk/predis#350]
Redis 3.2.0
Predis v1.1 current
PHP 5.5.9

> luliang@luliang-VirtualBox:~/gitlocaldir/predis$ phpunit 
> PHPUnit 3.7.28 by Sebastian Bergmann.
> 
> Configuration read from /home/luliang/gitlocaldir/predis/phpunit.xml.dist
> .............................................................   61 / 2249 (  2%)
> .............................................................  122 / 2249 (  5%)
> ......
> ............................................................. 1647 / 2249 ( 73%)
> ...........................................PHP Fatal error:  Call to undefined method Predis\Connection\Aggregate\SentinelReplicationTest::assertArraySubset() in /home/luliang/gitlocaldir/predis/tests/Predis/Connection/Aggregate/SentinelReplicationTest.php on line 47
> PHP Stack trace:
> PHP   1. {main}() /usr/bin/phpunit:0
> PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
> PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
> PHP   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:176
> PHP   5. PHPUnit_Framework_TestSuite->run() /usr/share/php/PHPUnit/TextUI/TestRunner.php:349
> PHP   6. PHPUnit_Framework_TestSuite->run() /usr/share/php/PHPUnit/Framework/TestSuite.php:705
> PHP   7. PHPUnit_Framework_TestSuite->runTest() /usr/share/php/PHPUnit/Framework/TestSuite.php:745
> PHP   8. PHPUnit_Framework_TestCase->run() /usr/share/php/PHPUnit/Framework/TestSuite.php:775
> PHP   9. PHPUnit_Framework_TestResult->run() /usr/share/php/PHPUnit/Framework/TestCase.php:783
> PHP  10. PHPUnit_Framework_TestCase->runBare() /usr/share/php/PHPUnit/Framework/TestResult.php:648
> PHP  11. PHPUnit_Framework_TestCase->runTest() /usr/share/php/PHPUnit/Framework/TestCase.php:838
> PHP  12. ReflectionMethod->invokeArgs() /usr/share/php/PHPUnit/Framework/TestCase.php:983
> PHP  13. Predis\Connection\Aggregate\SentinelReplicationTest->testParametersForSentinelConnectionShouldNotUseDatabaseAndPassword() /usr/share/php/PHPUnit/Framework/TestCase.php:983
> 

I'm not familiar with `phpunit` enough to figure out the reason why. So, looking forward to your responses.

**Comment by SpacePossum** [comment]
`assertArraySubset` is a method added to PHPUnit 4.4.0, you are running the test with PHPUnit 3.7.28.
While this case could be handled a bit better in the test I've to say PHPUnit 3.x is pretty old (current stables are 4.x and 5.x lines).

**Comment by nrk** [comment]
As pointed by @SpacePossum you are running an ancient version of phpunit while Predis [requires phpunit 4.8.0](https://github.com/nrk/predis/blob/v1.1.0/composer.json#L21-L23). If you cloned the repository then you can just `cd` into it and run `composer install`, this will fetch the correct version of phpunit into the `vendor` directory (this will not touch your global phpunit installation) so that you can just run `vendor/bin/phpunit`.
