### ISSUE TITLE
can not connect to twemproxy 

### ISSUE THREAD

**Issue by ralphQi** [nrk/predis#351]
error message is : 
Error while reading line from the server.

I am sure the redis-server is working good.

**Comment by nrk** [comment]
Twemproxy acts just like Redis so Predis doesn't really care. Could you be more specific and post the actual command that generated the error? If you get an exception with the message `Error while reading line from the server` it means that the connection was successful and Predis was able to send a command, but couldn't get a response from Redis in a reasonable time (most likely the connection timed out while waiting for the response or the client got disconnected by the server).

**Comment by nrk** [comment]
Any update?

**Comment by nrk** [comment]
Closing due to lack of feedback.
