### ISSUE TITLE
How to verify client side partitioning?

### ISSUE THREAD

**Issue by ahdavis** [nrk/predis#354]
This just a question, not an issue.  This question originally posted here:

http://stackoverflow.com/questions/38022064/how-to-verify-client-side-partitioning-with-predis

I am attempting to use client side partitioning via Predis. Everything seems to be working, but how can I verify values are being stored on multiple servers? I'd like to be able to list all keys on each server, but don't see how to in the predis documentation. I'm try to do a simple info call but get exception errors:

`$predisClient->info()` generates an "Cannot use 'INFO' over clusters of connections" exception. (This does work when using one server.)

`$predisClient->executeRaw( ['CLUSTER INFO'] )` generates an "Cannot use 'CLUSTER INFO' over clusters of connections" exception.

My `$predisClient` is defined as follows:

`$predisClient = new Predis\Client(['tcp:://127.0.0.1', 'tcp://<REMOTE SERVER IP HERE>']);`

I'm using redis 3.0.7, and predis 1.1.

Thank you

**Comment by nrk** [comment]
Considered that you are using Predis v1.1 you can simply do:

```php
foreach ($client as $node) {
    $info = $node->info('keyspace');
    // ...
}
```

This will work with both redis-cluster and a client-side sharded cluster. Please note that you configured the client to use the latter but `CLUSTER INFO` is only supported by redis-cluster (you'd need to direct this command to a specific node anyway since this command does not carry any key meaning that Predis has no way to calculate a slot).

**Comment by ahdavis** [comment]
Awesome, thank you very much! I didn't realize I could loop though the $client.

Fyi, because of the Predis session handler, I was able to migrate my apps from PHP 5.6 using memcached to PHP 7.x using redis. Thank you for that too!

**Comment by timsengit** [comment]
"Cannot use 'CLUSTER INFO' over clusters of connections"
it occur in this case:

`$parameters = ['tcp://r-xxxx..com'];

$client = new Predis\Client($parameters);`

**we can fix it by replace $parameters array to string like this**:
`$parameters = 'tcp://r-xxxx..com';

$client = new Predis\Client($parameters);`
