### ISSUE TITLE
 local.ERROR: Predis\Connection\ConnectionException: `SELECT` failed: ERR Server Error. 

### ISSUE THREAD

**Issue by yuchao86** [nrk/predis#355]
[2016-06-27 17:37:11] local.ERROR: Predis\Connection\ConnectionException: `SELECT` failed: ERR Server Error. [tcp://c7fb605cfb174293.m.cnbja.kvstore.aliyuncs.com:6379] in /data/www/cloudclass-api/vendor/predis/predis/src/Connection/AbstractConnection.php:155
Stack trace:
#0 /data/www/cloudclass-api/vendor/predis/predis/src/Connection/StreamConnection.php(263): Predis\Connection\AbstractConnection->onConnectionError('`SELECT` failed...', 0)
#1 /data/www/cloudclass-api/vendor/predis/predis/src/Connection/AbstractConnection.php(180): Predis\Connection\StreamConnection->connect()
#2 /data/www/cloudclass-api/vendor/predis/predis/src/Connection/StreamConnection.php(288): Predis\Connection\AbstractConnection->getResource()
#3 /data/www/cloudclass-api/vendor/predis/predis/src/Connection/StreamConnection.php(394): Predis\Connection\StreamConnection->write('*2\r\n$3\r\nGET\r\n$4...')
#4 /data/www/cloudclass-api/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\Connection\StreamConnection->writeRequest(Object(Predis\Command\StringGet))
#5 /data/www/cloudclass-api/vendor/predis/predis/src/Client.php(331): Predis\Connection\AbstractConnection->executeCommand(Object(Predis\Command\StringGet))
#6 /data/www/cloudclass-api/vendor/predis/predis/src/Client.php(314): Predis\Client->executeCommand(Object(Predis\Command\StringGet))
#7 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(54): Predis\Client->__call('get', Array)
#8 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(129): Illuminate\Cache\RedisStore->get('7f0ddddf627ce6e...')
#9 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(113): Illuminate\Cache\Repository->get('7f0ddddf627ce6e...')
#10 [internal function]: Illuminate\Cache\Repository->has('7f0ddddf627ce6e...')
#11 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(296): call_user_func_array(Array, Array)
#12 /data/www/cloudclass-api/vendor/tymon/jwt-auth/src/Providers/Storage/IlluminateCacheAdapter.php(57): Illuminate\Cache\CacheManager->__call('has', Array)
#13 /data/www/cloudclass-api/vendor/tymon/jwt-auth/src/Blacklist.php(74): Tymon\JWTAuth\Providers\Storage\IlluminateCacheAdapter->has('7f0ddddf627ce6e...')
#14 /data/www/cloudclass-api/vendor/tymon/jwt-auth/src/JWTManager.php(83): Tymon\JWTAuth\Blacklist->has(Object(Tymon\JWTAuth\Payload))
#15 /data/www/cloudclass-api/vendor/tymon/jwt-auth/src/JWTAuth.php(190): Tymon\JWTAuth\JWTManager->decode(Object(Tymon\JWTAuth\Token))
#16 /data/www/cloudclass-api/vendor/tymon/jwt-auth/src/JWTAuth.php(124): Tymon\JWTAuth\JWTAuth->getPayload(false)
#17 /data/www/cloudclass-api/app/Http/Middleware/AfterOperatingLog.php(27): Tymon\JWTAuth\JWTAuth->authenticate()
#18 [internal function]: App\Http\Middleware\AfterOperatingLog->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#21 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /data/www/cloudclass-api/vendor/barryvdh/laravel-cors/src/HandleCors.php(42): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#26 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#28 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request))
#34 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /data/www/cloudclass-api/vendor/barryvdh/laravel-cors/src/HandleCors.php(42): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#39 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#44 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#46 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#48 /data/www/cloudclass-api/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#49 /data/www/cloudclass-api/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#50 {main}

**Comment by nrk** [comment]
You could have at least described the issue instead of blatantly pasting an exception. How did you configure the client? It seems like you passed an invalid value for the `database` parameter (e.h. a DB index out of the range configured in `redis.conf`).

**Comment by yuchao86** [comment]
this is my controller,  
Route::get('/test', function(){
    Cache::put('name', 'Taylor', 60); //error！

    $name = Cache::get('name'); 

    echo $name;
});
when I was used redis-cli call my redis-server ,everything is ok, I used the phpunit test the redis server ,all is right.
But while I was make refresh the API many times, sometimes ok, another time failed..???

**Comment by lulyon** [comment]
@yuchao86 The above controller code  is not where predis client get initialized.

**Comment by yuchao86** [comment]
which number the newest release version predis ?

**Comment by lulyon** [comment]
@yuchao86  Corrently it is v1.1.1, please refer to https://github.com/nrk/predis/releases

**Comment by papa-smurf** [comment]
We are experiencing the exact same issue on 1.1.1 using Amazon ElastiCache

**Comment by nrk** [comment]
@yuchao86 the problem is that this is __not__ an issue of Predis, as [you can see here](https://github.com/nrk/predis/blob/v1.1.1/src/Connection/StreamConnection.php#L260-L264) the string `ERR Server Error` is an actual response payload returned by Redis: it's Redis that it's having some kind of issue, but the response message is way too generic to tell what's wrong. The fact that Predis was able to connect to Redis and tell you by throwing an exception that Redis returned an error means that Predis is actually working fine.

@papa-smurf I guess it's only a coincidence as it wouldn't make any sense: the only [changes between v1.1.0 and v1.1.0](https://github.com/nrk/predis/compare/v1.1.0...v1.1.1) involved completely unrelated parts of the library.

**Comment by papa-smurf** [comment]
@nrk Looking at the chanelog I'd have to agree with you. Funny thing is that 1.1.0 still works though, and 1.1.1 doesn't. Any idea on what might cause this issue in order for us to better debug this behavior?

**Comment by nrk** [comment]
@papa-smurf I have no idea because, as I've said, there's no valid reason for it to break upgrading rom v1.1.0 to v1.1.1... can you please post a full stacktrace of the exception? I'm not even sure it's related to this very same issue.

**Comment by ultimateck** [comment]
Same issue with connecting to heroku redis with laravel app using v1.1.1
[Predis\Connection\ConnectionException]                                                        
  `SELECT` failed: ERR invalid DB index [tcp://ec2-54-225-115-56.compute-1.amazonaws.com:10759]

downgraded versions are working fine.

**Comment by nrk** [comment]
@ultimateck your case is not the same and it's not an issue: `ERR invalid DB index` means that you have specified a database index out of the range of the maximum number of logical databases configured for redis (the [default value in `redis.conf`](https://github.com/antirez/redis/blob/3.2.0/redis.conf#L174-L177) is `16`). If you are coming from Predis < v1.1.0, the `-ERR` response returned by Redis was simply being silently swallowed by the client and all of your reads / writes effectively ended up on the default database `0`.

**Comment by nrk** [comment]
Closing due to lack of feedback.

**Comment by CaptionXian** [comment]
SELECT` failed: ERR unknown command 'SELECT' [tcp://***.108.239.44:26382]？   why?

**Comment by itsmylab** [comment]
I might be bumping a old thread, but for me setting`REDIS_CACHE_DB` to 0 sorted things out

**Comment by r9software** [comment]
I configured this laravel app with direct connection to a redis server and setting up REDIS_CACHE_DB = 0 on the env fixed it.
but it was too hard to find this post
