### ISSUE TITLE
Confirmation of prefixes and maxmemory

### ISSUE THREAD

**Issue by ahdavis** [nrk/predis#356]
I am using Predis 1.1 (and PHP 7.0.7) for session handling and data caching.  I would like to use a different prefix for each.  I assume that I have to create two separate clients, but wanted to confirm that there's no way to use a different prefix for session and data caching with one client.  Is his correct?  Also, is the maxmemory configuration value shared among all clients I create?

Thank you

**Comment by nrk** [comment]
You must indeed use two separate client instances.
What do you mean by maxmemory?

**Comment by ahdavis** [comment]
I'm sorry I was not clear.  I was referring to the maxmemory value in /etc/redis.conf.  Do all instantiated predis clients share the maxmemory limit?  E.g. If I create a predis client for session handling and a predis client for application data caching (both in the same php script with different prefixes), will the predis clients share the 100mb maxmemory limit?  I'm assuming they share it, but just wanted to confirm.  Thank you.

**Comment by nrk** [comment]
`maxmemory` is a __server__ setting that imposes an hard memory limit for the running Redis instance, from the point of view of clients it's completely transparent. Setting `maxmemory` is fine when storing cache data, but I don't think it's good for sessions as session keys could be unexpectedly evicted by Redis. You might want to use two separate Redis instances in this case, one using `maxmemory` in its `redis.conf` file for the volatile cache and one without `maxmemory` for sessions.
