### ISSUE TITLE
pear.nrk.io doesn't work on IPv6

### ISSUE THREAD

**Issue by yunosh** [nrk/predis#358]
Title says it all. pear.nrk.io times out on 2a01:7e01::f03c:91ff:fe0a:d15b and only works on 139.162.175.220

**Comment by nrk** [comment]
@yunosh I see quite a lot of HTTP 200 entries coming from different IPv6 hosts in the log of my webserver, are you sure?

**Comment by cebe** [comment]
`pear.nrk.io` responds fine for me on ipv6.

**Comment by yunosh** [comment]
Weird.
´´´
$ ping pear.nrk.io
PING pear.nrk.io (139.162.175.220) 56(84) bytes of data.
64 bytes from oh.noes.timeparadox.it (139.162.175.220): icmp_seq=1 ttl=54 time=373 ms
64 bytes from oh.noes.timeparadox.it (139.162.175.220): icmp_seq=2 ttl=54 time=216 ms
64 bytes from oh.noes.timeparadox.it (139.162.175.220): icmp_seq=3 ttl=54 time=264 ms
64 bytes from oh.noes.timeparadox.it (139.162.175.220): icmp_seq=4 ttl=54 time=338 ms
64 bytes from oh.noes.timeparadox.it (139.162.175.220): icmp_seq=5 ttl=54 time=359 ms
64 bytes from oh.noes.timeparadox.it (139.162.175.220): icmp_seq=6 ttl=54 time=220 ms
^C
--- pear.nrk.io ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 9793ms
rtt min/avg/max/mdev = 216.904/295.503/373.143/64.188 ms
$ ping6 pear.nrk.io
PING pear.nrk.io(oh.noes.timeparadox.it) 56 data bytes
^C
--- pear.nrk.io ping statistics ---
28 packets transmitted, 0 received, 100% packet loss, time 26999ms
´´´
Must be some issue with my provider then.

**Comment by nrk** [comment]
I guess I can close this issue then, but feel free to post an update if necessary.
