### ISSUE TITLE
wrong result commnad SCARD with sentinel

### ISSUE THREAD

**Issue by kim109** [nrk/predis#359]
I am sorry for my poor english.

I am using Predis 1.1 with PHP 5.6.23

I have big data type Set. ( total : 1,477,630 ) 
run SCARD result "1,450" ( with sentinel )
so i connect direct, and run SCARD result 1,477,630 is good result.

**Comment by nrk** [comment]
This is hardly a Predis issue, but to make sure you should connect directly via `redis-cli` (thus bypassing any library) to the master server and the slaves and check that the keyspace is properly replicated from the master.

**Comment by nrk** [comment]
Any update?

**Comment by kim109** [comment]
sorry, my mistake! 

test env is  other database.

thx!
