### ISSUE TITLE
sentinel config problem

### ISSUE THREAD

**Issue by aegeansea** [nrk/predis#360]
code like this:
    \Predis\Autoloader::register();
    $sentinels = ['tcp://127.0.0.1:10005', 'tcp://127.0.0.1:10006'];
    $options = [
        'replication' => 'sentinel',
        'service' => 'mymaster',
    ];
    $client = new \Predis\Client($sentinels, $options);
    $client->set('foo', 'bar');
    $value = $client->get('foo');

then cause an error:
An instance of type 'Predis\Connection\Aggregate\ReplicationInterface' was expected.

FILE: /home/tellmewhy/www/ThinkPHP/Library/Predis/Configuration/ReplicationOption.php 　LINE: 49

I read part of the relevant code,seems `$value` eq sentinel can`t be the right config.poor english,sry!

**Comment by nrk** [comment]
You should at leat indicate which version of Predis you are using.

**Comment by aegeansea** [comment]
1.0.4 from `predis\VERSION` file,

**Comment by nrk** [comment]
Predis v1.0.4 does not support sentinel, you should upgrade to v1.1.

**Comment by aegeansea** [comment]
thx very much.
