### ISSUE TITLE
No submodule mapping found in .gitmodules

### ISSUE THREAD

**Issue by sQuarecoW** [nrk/predis#361]
When I add Predis with composer, my git client throws an error:

`fatal: no submodule mapping found in .gitmodules for path 'sources/ext/composer/vendor/predis/predis'`

**Comment by nrk** [comment]
@sQuarecoW shouldn't this issue rather be filed on [composer/composer](https://github.com/composer/composer/issues)? And by the way we never used git submodules in the Predis repository...

**Comment by sQuarecoW** [comment]
Maybe, it just happened when I loaded Predis via Composer.. I downloaded the zip and I don't get an error..

**Comment by nrk** [comment]
@sQuarecoW I don't know, but I'm pretty sure this is not related to Predis or something under our control.
