### ISSUE TITLE
First connection seems broken

### ISSUE THREAD

**Issue by NiclasHedam** [nrk/predis#362]
Hello,

The first time I'm connecting to the redis server in a long time, this happens:
`staging.ERROR: exception 'Predis\Connection\ConnectionException' with message 'Error while reading line from the server. [tcp://web-redis:6379]' in /usr/share/nginx/html/vendor/predis/predis/src/Connection/AbstractConnection.php:155`

After a refresh, everything works like a charm. I can't seem to find out if this is a redis issue or php/predis issue. My configurations looks like this
```
'redis' => [
        'cluster' => false,
        'default' => [
            'host' => 'web-redis',
            'password' => null,
            'port' => '6379',
            'database' => 0,
            'read_write_timeout' => -1
        ],

    ],
```

I'm running predis v1.1.1 on Laravel v5.2.39

**Comment by nrk** [comment]
There shouldn't be any difference between the first connection and subsequent connections, moreover the error _Error while reading line from the server_ actually means that the client was able to connect successfully to the server and send a command but failed to read back the response due to a network error. Does the same happen when using the PHP CLI?

**Comment by NiclasHedam** [comment]
I'm not able to try running it in CLI in the environment, where it is happening. I did find out though, that keeping the connection open by continuingly visiting the page will not render this issue. It seems like it is happening, when the connection is no longer kept alive.

**Comment by nrk** [comment]
@NiclasHedam there's no apparent reason attributable to the client library for such a behaviour, and unfortunately I can't investigate it without being able to reproduce your issue. Could you try to remove `read_write_timeout` from the connection parameters?

**Comment by nrk** [comment]
Any update?

**Comment by NiclasHedam** [comment]
I have not yet found any solution, but I'm sure now the predis library has nothing to do with this.
