### ISSUE TITLE
ConnectionException

### ISSUE THREAD

**Issue by bertZ** [nrk/predis#365]
I'm getting a "PHP Fatal error:  Uncaught Predis\Connection\ConnectionException" running the following code using an invalid connection url even when using the try-catch:

```
$this->client = new Client($redisUrl);

try {
	$this->client->connect();
	$this->log->addInfo("Redis connection is ready.");
} catch (Predis\Connection\ConnectionException $exception) {
	$this->log->addError("Couldn't connect to redis, please check your settings");
}
```

What could it be?

**Comment by GrahamCampbell** [comment]
Are you inside a namespace? Did you missing a leading slash on that catch statement?

**Comment by bertZ** [comment]
Oh... I forgot that leading slash was needed when inside a namespace... Thank you very much.
