### ISSUE TITLE
Persistence support with Sentinels?

### ISSUE THREAD

**Issue by mmucklo** [nrk/predis#366]
This is half-question half-request - 

First - thank you for adding Sentinel support to Predis.  I'm looking at using this library again due to this awesome feature, however I have a few questions -

First - do you support any type of persistence connections with Sentinels?

What I'd be looking for I suppose is something that creates a persistent connection to the master / slaves and only reconnects to the sentinel if the connection goes away, or the ROLE changes...

Ultimately what I'm looking for is any way to minimize the overhead of sentinel communication...

**Comment by nrk** [comment]
@mmucklo if by _persistent connection_ you mean the same concept of persistent connections used by PHP, then yes it's possibile: just use `persistent=1` in the parameters array. But aside from that, there's no way for clients connected to Redis nodes to receive events about the state of the replication configuration in an asynchronous way, which means that clients must always ask to a sentinel if a particular server matches the expected role before trying to do anything.

That said, redis-sentinel actually provides an API to check the health of master and slave nodes using notifications via the usual PUB/SUB pattern. It is thus possible to detect changes in the replication configuration at run time but you should have a dedicated asynchronous client (which would become the single point of failure in the setup) that rewrites the configuration of replication used by your PHP application whenever something changes. It's kind of a different approach that I never had the time to play with.
