### ISSUE TITLE
Using AUTH with clusters/replication

### ISSUE THREAD

**Issue by tillkruss** [nrk/predis#368]
I can't find any info on this in the docs.

What's the correct way of setting the password for a redis cluster *and* when using replication?

Can a different password be set for each server, or only a shared one in each case? 

Thanks!

**Comment by nrk** [comment]
@tillkruss when using redis-cluster and redis-sentinel all of the nodes must share the same password which means that there's no point in having the ability to specify a different password for each server. You must provide a single shared password using the `parameters` client option as [described in the README](https://github.com/nrk/predis/blob/v1.1.1/README.md#replication) (although described in the paragraph related to replication, the same is valid for the redis-cluster backend).

```php
$client = new Predis\Client($parameters, [
    'cluster' => 'redis',
    'parameters' => [
        'password' => $secretpassword,
    ],
]);
```

**Comment by tillkruss** [comment]
Great, thanks a lot!
