### ISSUE TITLE
SentinelReplication: Any reason for $retryLimit = 20? 

### ISSUE THREAD

**Issue by lulyon** [nrk/predis#375]
Predis\Connection\Aggregate\SentinelReplication.php

> /**
>      \* Max number of automatic retries of commands upon server failure.
>      *
>      \* -1 = unlimited retry attempts
>      \*  0 = no retry attempts (fails immediatly)
>      \*  n = fail only after n retry attempts
>      *
>      \* @var int
>      */
>     protected $retryLimit = 20;

Seems **too many retries** here if `getconnection` fail. Any reason for this?

**Comment by nrk** [comment]
A server that failed right away may not be evicted immediatly by sentinels, which means there's a window of a few seconds when you might still get a dead node when asking for the master or a slave. The default retry limit here is kind of arbitrary based on some tests but you can customize it by using the public method `SentinelReplication::setRetryWait()`. Do you have suggestion, based on tests, of a a more appropriate default value?

**Comment by nrk** [comment]
Closing due to lack of feedback, but feel free to reopen if needed.

**Comment by amran08** [comment]
@nrk 

"but you can customize it by using the public method SentinelReplication::setRetryWait() "

Shouldn't I able to pass this as connection property ?
