### ISSUE TITLE
Question: finding BITPOS

### ISSUE THREAD

**Issue by HankBrown** [nrk/predis#377]
v1.1.1 (2016-06-16)

```
$redis = new Predis\Client([...]);

$redis->bitpos(); // method not found
$redis->StringBitPos(); // method not found

```
Release notes say it was added.
In general I don't understand how we find a command.
I see some command at the redis site, I want to try it with Predis.... 
 sometimes the method name is the same, and sometimes I go in circles. 
As in the example above.

Thanks in advance for any advice.

`Uncaught exception 'Predis\Response\ServerException' with message 'ERR unknown command 'BITPOS'
`

**Comment by nrk** [comment]
The proper method to use is indeed `$redis->bitpos(...)` and it's been added to Predis a few releases ago, but you must make sure that the version of Redis server you are connecting to is at least >= 2.8.7 since it's been implemented in that release.
