### ISSUE TITLE
eval() not working

### ISSUE THREAD

**Issue by khromov** [nrk/predis#382]
- Predis version: `1.1.1`
- `redis_version:3.2.4`
- `PHP 7.0.10 (cli)`
- OSX Yosemite

I'm using Predis as a dependency (via Laravel / Lumen) and am having issues with the `eval()` command. When Predis runs `eval()`, Redis does not respond, and the connection hangs.

Here is an example of the call we are using:

Project:  

``` php
$predis->->eval(LuaScripts::size(), 3, $queue, $queue.':delayed', $queue.':reserved')
```

LuaScripts class:  

``` php
<?php
namespace Illuminate\Queue;

class LuaScripts
{
    /**
     * Get the Lua script for computing the size of queue.
     *
     * @return string
     */
    public static function size()
    {
        return <<<'LUA'
return redis.call('llen', KEYS[1]) + redis.call('zcard', KEYS[2]) + redis.call('zcard', KEYS[3])
LUA;
    }
}

```

**Comment by nrk** [comment]
Did you try the very same Lua script directly within `redis-cli` to make sure that it works as expected?

**Comment by khromov** [comment]
@nrk No, I did not try that. The problem resolved itself upon a reboot, but I was able to reproduce the issue on a second computer with the same configuration, so there is something about installing Redis on OSX that makes LUA scripts not work until you reboot. Self-closing this.

**Comment by nrk** [comment]
@khromov I see, thanks.
