### ISSUE TITLE
HTTP 500 error 

### ISSUE THREAD

**Issue by skittelz102** [nrk/predis#386]
I was working on putting predis in my website and I'm using version 5.6 PHP and Version 1.1 predis. I started by commenting out certain parts of the code and it figured out it was line 6 and 7 being commented out would stop the error and the connection to the server was on lines 6-22. 
[servers.zip](https://github.com/nrk/predis/files/536660/servers.zip)

**Comment by nrk** [comment]
You are missing the namespace separators when using the fully qualified name of classes, that's basic PHP  so you should probably read some learning material about the language first.

**Comment by skittelz102** [comment]
That is an old file i did not upload the most recent but i did use namespace separators and it still was giving a http 500 error have you ever heard of this happening because of version compatibility issues?
