### ISSUE TITLE
The "phpiredis" extension is required by this connection backend.

### ISSUE THREAD

**Issue by marwanzak** [nrk/predis#387]
Hi,
I'm trying to make redis cluster using this code:
`$client = new Predis\Client($multiple_servers, [
    'cluster' => 'redis',
    'connections' => [
        'tcp'  => 'Predis\Connection\PhpiredisStreamConnection'
]]);`

I tried to install it from https://github.com/nrk/phpiredis but the same problem shows up.
Any help.

**Comment by nrk** [comment]
The client is configured correctly but check from the output of `phpinfo()` that `phpiredis` is indeed loaded by PHP at runtime, the only possible explanation is that you compiled phpredis but didn't configure PHP to load the extension.
