### ISSUE TITLE
`SELECT` failed: ERR invalid DB index  BUG db is db0

### ISSUE THREAD

**Issue by luoxun** [nrk/predis#390]
we are using laravel predis , but now we are having a problem as follow:
`SELECT` failed: ERR invalid DB index 

I use command line to connect ,it works fine, I use db0, set and get work fine;
but in laravel predis ,when i use db 0,  got a problem "`SELECT` failed: ERR invalid DB index 
"; when I changed it into db1 ,db2,......,it's fine

here is my predis version
predis/predis     v1.1.x-dev 0e17edb Flexible and feature-complete 
and this is my redis version
redis-server  redis_version:3.2.5 

pls tell me how to fix this ,thx a lot

**Comment by nrk** [comment]
I don't use Laravel so I don't know what it does under the hood to configure Predis but setting `database=0` in the connection parameters of `Predis\Client` works as expected. You should try using Predis alone and do the same to see if you get the same error response from Redis. If it works as expected, then this is not an issue related to Predis.

**Comment by JackSW** [comment]
@luoxun I just had a similar issue with laravel. When specifying the index, make sure to put the `0` in quotes, otherwise it just gets evaluated as `false` which ends up passing an empty string to the predis client.
`REDIS_DATABASE = 0` gets turned into `"database":""` and gives `ERR invalid DB index`
`REDIS_DATABASE = "0"` results in `"database":"0"` and works

**Comment by itsmylab** [comment]
I know I'm bumping a old thread, but for me setting `REDIS_CACHE_DB` to 0 sorted things out

**Comment by ybizeul** [comment]
Finally figured it out. not sure I understand though.

I'musing docker links, and naming my redis server : `redis`. That's an issue because of environment variable conflict, so I changed my redis server to `redis-server`.

But then I ried using just the `url` parameter as `tcp://redis-server:6379` but kept getting the same error.

I finally commented out `url`and use `host`and it works.

```
    'redis' => [

        'client' => env('REDIS_CLIENT', 'predis'),

        'options' => [
            'cluster' => env('REDIS_CLUSTER', 'predis'),
            'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
        ],

        'default' => [
            #'url' => 'tcp://redis-server:6379/',
            'host' => env('REDIS_HOST', 'redis-server'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => env('REDIS_DB', 0),
        ],
    ],
```

**Comment by osahady** [comment]
in .env file just add the following 
REDIS_CACHE_DB=0

and it works

**Comment by PetengDedet** [comment]
> > Finally figured it out. not sure I understand though.
> > I'musing docker links, and naming my redis server : `redis`. That's an issue because of environment variable conflict, so I changed my redis server to `redis-server`.
> > But then I ried using just the `url` parameter as `tcp://redis-server:6379` but kept getting the same error.
> > I finally commented out `url`and use `host`and it works.
> > ```
> >     'redis' => [
> > 
> >         'client' => env('REDIS_CLIENT', 'predis'),
> > 
> >         'options' => [
> >             'cluster' => env('REDIS_CLUSTER', 'predis'),
> >             'prefix' => env('REDIS_PREFIX', Str::slug(env('APP_NAME', 'laravel'), '_').'_database_'),
> >         ],
> > 
> >         'default' => [
> >             #'url' => 'tcp://redis-server:6379/',
> >             'host' => env('REDIS_HOST', 'redis-server'),
> >             'password' => env('REDIS_PASSWORD', null),
> >             'port' => env('REDIS_PORT', 6379),
> >             'database' => env('REDIS_DB', 0),
> >         ],
> >     ],
> > ```
> 
> THANKYOU!!! it work!

You saved my day

**Comment by Mllexx** [comment]
> in .env file just add the following
> REDIS_CACHE_DB=0
> 
> and it works

This worked for me thanks.

**Comment by pratik-nickelfox** [comment]
> I know I'm bumping a old thread, but for me setting `REDIS_CACHE_DB` to 0 sorted things out

Thank you so much.. :)

**Comment by MCKLtech** [comment]
+1 for adding REDIS_CACHE_DB equal to zero in the .env file (I'm using Heroku)

If anyone could explain why this would be the case, I'd be curous.

**Comment by rintoug** [comment]
> in .env file just add the following REDIS_CACHE_DB=0
> 
> and it works

This worked for me in Laravel Version 7

**Comment by obipascal** [comment]
Setting the `REDIS_CACHE_DB=1` or greater works fine!

**Comment by eskayamadeus** [comment]
> Setting the `REDIS_CACHE_DB=1` or greater works fine!

Brilliant. In my understanding, the value of REDIS_CACHE_DB just points to a name that should be used for the database. Therefore, any value at all should work, not just 0
