### ISSUE TITLE
how judge the connect is successful

### ISSUE THREAD

**Issue by ganxiangdong** [nrk/predis#400]
my code:
$client = new \Predis\Client($connect, $options);
var_dump($client->isConnected()); 
// output false forever，but it connect is successful actually

**Comment by nrk** [comment]
Please read the README:

> Connections to Redis are lazy meaning that the client connects to a server only if and when needed. While it is recommended to let the client do its own stuff under the hood, there may be times when it is still desired to have control of when the connection is opened or closed: this can easily be achieved by invoking $client->connect() and $client->disconnect(). Please note that the effect of these methods on aggregate connections may differ depending on each specific implementation.
