### ISSUE TITLE
Implement session locking

### ISSUE THREAD

**Issue by smilesrg** [nrk/predis#401]
Please implement session locking in this bundle.

**Comment by smilesrg** [comment]
Sorry, wrong repository

**Comment by nrk** [comment]
This is not a bundle but a framework-agnostic library, that said session locking is kind of beyond the scope of this library.

**Comment by norbe** [comment]
@smilesrg Did you solve session locking somehow?

**Comment by smilesrg** [comment]
@norbe please google "redis session locking" and find a solution for your framework, I did exactly like that, but I don't remember much details
