### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Predis\Client' not found in  vendor/laravel/framework/src/Illuminate/Redis/Database.php:62

### ISSUE THREAD

**Issue by alankarmore** [nrk/predis#406]
I am getting this issue even though I have installed this package via composer. Could you please help me how to resolve this. This is really necessary because it I am using redis as queue driver I am not able to send mail to users. Also I am not able to use Mail::queue feature..

**Comment by nrk** [comment]
You should ask these questions on a Laravel-oriented forum or support site. I've never used Laravel and I don't even know how it works internally.

**Comment by danicomsats077** [comment]
kjbkvk

**Comment by danicomsats077** [comment]
laravel.io is your friend...!
