### ISSUE TITLE
1.0.4: hmget keys are not set

### ISSUE THREAD

**Issue by jmkgreen** [nrk/predis#416]
Tiny fragment of code:

```
                $answer = $predis->hMGet($key, array('LastSyncAt', 'HostName', 'HostIp'));
```

I am now expecting to iterate thus:

```
                foreach ($answer as $field => $value) {
                    if ($field == 'LastSyncAt') {
                    }
                    if ($field == 'HostName') {
                        $account->setClientHostName($value);
                    }
                    if ($field == 'HostIp') {
                        $account->setClientHostIp($value);
                    }
}
```
Instead, I'm looking at the following as `$answer`:

```
array (
  0 => '2017-02-28T14:58:27+00:00',
  1 => 'DEV001',
  2 => '192.168.99.1',
)
```

Here's the bit that writes the key:

```
if (isset($redis) && isset($config_data['identity'])) {
    $value = array (
        'Identity' => $config_data['identity'],
        'LastSyncAt' => date('c')
    );
    if (isset($customer->hostname)) {
        $value['HostName'] = $customer->hostname;
    }
    if (isset($customer->ipaddress)) {
        $value['HostIp'] = $customer->ipaddress;
    }
    $redis->hmset("Account:Dispatcher:".$customer->userid, $value);
}
```

Am I doing something crazy myself?

**Comment by nrk** [comment]
If you look at the docs of [`HMGET`](https://redis.io/commands/hmget), Redis returns the list of values of the specified fields without the actual fields names, that's why Predis returns an array and not a named array. As a solution, you could use [`array_combine()`](http://php.net/manual/en/function.array-combine.php) on the returned response with something like this: `$dictionary = array_combine($fields, $answer)`.

**Comment by jmkgreen** [comment]
Right. In my defence (and acknowledgement of error), Google for "Predis hmget" and I found the most direct documentation was:

* https://github.com/phpredis/phpredis#hmget

Which is exactly what I wrote that snippet of code to. I guess _phpredis_ are just doing the `array_combine` ahead of returning the response.

**Comment by nrk** [comment]
@jmkgreen yes sometimes phpredis does things that are a bit different than the standard behaviour of Redis by manipulating the actual response coming from the server, like in this specific case. I'm not a fan of this approach, I mean it may be convenient in some cases but I still prefer to stick as much as possible with what Redis defines, at least for commands (higher-level abstractions built upon them are a whole different story).

**Comment by jmkgreen** [comment]
That's fine - it is a little embarrassing that I didn't spot that I was referencing an example from an alternate project! Even a colleague didn't spot that small detail before I posted this issue :-)
