### ISSUE TITLE
Unable to pass client parameters as array for sentinel

### ISSUE THREAD

**Issue by jhnlsn** [nrk/predis#425]
When initiating a `new Client`, i'm not able to pass in an array as the first parameter for use with sentinel replication.

the issue is with this code here: https://github.com/nrk/predis/blob/v1.1/src/Client.php#L114

```
if (!isset($parameters[0])) {
                return $this->options->connections->create($parameters);
            }
```

I can work around this by initializing the client like this for now:

```
$redis = new Client( [0 => 'dummy', 'scheme' => 'tcp, ...], ['replication' => 'sentinel', 'services' =>'myservice']);
```

I found this when trying to bypass a timeout bug mentioned in my other ticket.

**Comment by jhnlsn** [comment]
I figured it out and maybe this will help someone else if they come across the same issue!


if you want to use a connection array, you need to pass in an array of arrays for sentinel!

so this:
```
$redis = new Client(['tcp://127.0.0.1:6379'], ['replication'=>'sentinel', 'services' => 'myservice']);
```

would translate to this!
```
$redis = new Client([
['scheme' => 'tcp', 'host' => '127.0.0.1', 'port'=> '6379']
],['replication'=>'sentinel', 'services' => 'myservice'])
```

**Comment by nrk** [comment]
Well it's written in the README 😃 Do you think the wording used there should be improved?
