### ISSUE TITLE
please create a GitHub OAuth token to go over the API rate limit????

### ISSUE THREAD

**Issue by edgework** [nrk/predis#438]
Attempting to install, got this:

Could not fetch https://api.github.com/repos/nrk/predis/zipball/f0210e38881631afeafb56ab43405a92cafd9fd1, please create a GitHub OAuth token to go over the API rate limit

**Comment by nrk** [comment]
I guess you are using composer (you should've described the whole context in which you get that message at least), [found this](https://github.com/composer/composer/issues/3542#issuecomment-67623002) after a 5-seconds search on Google.

**Comment by AkashicSeer** [comment]
Sarcasm is expected from assholes

**Comment by nrk** [comment]
@AkashicSeer except it wasn't sarcasm and I really did have to search for an answer myself at that time, and apparently it was quite easy to find one 🤷 Have a good day.
