### ISSUE TITLE
Documentation & Docblocks

### ISSUE THREAD

**Issue by gsdevme** [nrk/predis#439]
Hey,

Im trying to run some static analysis against some code using the predis library, however Im struggling to workout certain arguments for methods.

For example we have some existing code using `zadd(KEY, SCORE, VALUE)` but then doesn't match the docblock. 

```
 * @method int    zadd($key, array $membersAndScoresDictionary)
```

Looking at the unit tests its invalid against the docblocks.

```
$redis->zadd('type:zset', 0, 'foobar');
$this->assertEquals('zset', $redis->type('type:zset'));
```

Looking at the actual code its a little cryptic,  

```
    protected function filterArguments(array $arguments)
    {
        if (is_array(end($arguments))) {
            foreach (array_pop($arguments) as $member => $score) {
                $arguments[] = $score;
                $arguments[] = $member;
            }
        }
        return $arguments;
    }
```

However If I actually pass an array like the docblocks state something funny happens 

https://3v4l.org/1Jkmk

Is it just just a case the docblock is wrong?

**Comment by nrk** [comment]
See #89 for details and an explanation on the current situation, but Predis accepts multiple signatures for Redis commands handled by the `__call` magic medhod.  As for how arguments of `ZADD` are handled, it should be noted that in the docblock the array variable is named _`$membersAndScoresDictionary`_ which means that it expects a named array of `$score => $member` pairs.
