### ISSUE TITLE
$redis->set fails, exits with no output or error

### ISSUE THREAD

**Issue by benbowler** [nrk/predis#440]
Good afternoon, I'm using Predis with composer as part of a Herbert structured Wordpress plugin. Predis says that it is correctly connected to the datastore but the set command exits without any information or error and when using the redis-cli no data is stored.
- version of Predis: 1.1
- version of Redis: 3.2.8
- version of PHP: 5.6 
 - name and version of the operating system: Ubuntu 14.04.2 LTS through Vagrant on Mac OS X El Capitan 10.11.6 host
 - when possible, a small snippet of code that reproduces the issue.:

```
<?php namespace RedisTestPlugin\Services;

use \WP_CLI;

class Redirect {

  public function testRedis() {

    var_dump('here');

    \Predis\Autoloader::register();

    // since we connect to default setting localhost
    // and 6379 port there is no need for extra
    // configuration. If not then you can specify the
    // scheme, host and port to connect as an array
    // to the constructor.
    try {
        $redis = new \Predis\Client(getenv('BFR_REDIS_CONNECTION_STRING'));

        echo "Successfully connected to Redis";
    }
    catch (Exception $e) {
        echo "Couldn't connected to Redis";
        echo $e->getMessage();
    }

    $redis = new \Predis\Client(getenv('BFR_REDIS_CONNECTION_STRING'));

    var_dump('here');

    $redis->set("hello_world", "Hi from php!");

    var_dump('$redis->set');

    $value = $redis->get("hello_world");
        var_dump('$redis->get');
    var_dump($value);

    echo ($redis->exists("Santa Claus")) ? "true" : "false";

    // Set then get the set key
    die(var_dump(self::$redis->set($from, $to)));
  }

}

new Redirect(); // Create class and connect to Redis

```

Output I get:

```
/vagrant/web/app/dev/redis-test-plugin/app/Services/Redirect.php:66:string 'here' (length=4)
Successfully connected to Redis
/vagrant/web/app/dev/redis-test-plugin/app/Services/Redirect.php:87:string 'here' (length=4)
```

Nothing else with all error reporting on.

If you need any more information let me know.

**Comment by nrk** [comment]
Not really sure what you are trying to attempt in that snippet but I removed the class wrapping and the last `die()` and it works as expected I'd say, no errors whatsoever. Try connecting to your Redis server using the `redis-cli` utility in the command line and issue a [`MONITOR`](https://redis.io/commands/monitor) command, then execute your scripts and you should see the exact commands sent to Redis by PHP.

**Comment by benbowler** [comment]
It doesn't even hit Redis, it just dies without error or output. I'll investigate and let you know what I find.

**Comment by benbowler** [comment]
It was an incorrect connection string I would have expected an error from the client or from a command but instead I got silence.

**Comment by nrk** [comment]
The connection to Redis is not established when doing `new Predis\Client();` but when the first command is executed or when `$client->connect()` is invoked explicitly. That said, if the connection string is wrong and points to a wrong host/port pair then you should indeed see at least an exception if the connection fails when trying to execute the first command. If it's not the case the I guess there's something in your code that swallows exceptions.
