### ISSUE TITLE
@method entry for transaction() missing in ClientInterface

### ISSUE THREAD

**Issue by mirfilip** [nrk/predis#455]
Hi,
I noticed `ClientInterface` doesn't have a `@method` docblock annotation for `__call` autocompletion but actual implementation has that method.

Is that an oversight is it actually for a reason?

**Comment by nrk** [comment]
The `@method` attribute is used to define which magic methods are handled by the implementation of the `__call()` metamethod, on the other hand `__call()` is an actual method so [it has its own docblock](https://github.com/nrk/predis/blob/v1.1.1/src/ClientInterface.php#L229-L238).
