### ISSUE TITLE
sometime notify 'dbUnknown response prefix'

### ISSUE THREAD

**Issue by JulyXing** [nrk/predis#457]
sometime redis notify 
```
"dbUnknown response prefix: 'u'. [tcp://host]"
```
the prifix is not fixed

**Comment by nrk** [comment]
This is most likely a protocol synchronization issue, but it's impossibile to debug without a script to reproduce the issue. Are you using persistent connections?

**Comment by nrk** [comment]
Closing due to lack of feedback.
