### ISSUE TITLE
Is it possible to disable cluster for running SCRIPT?

### ISSUE THREAD

**Issue by brunokk** [nrk/predis#461]
Hello,

I have been using Predis v0.85 for a long time. It has been working very very well. I had to update to use ZRANGEBYLEX, and now with v1.1, my scripts in Redis don't run anymore, such as:

$resultRedis = $redisHandle->script('load', $luaScript);		// Store Lua Script in Server and get SHA

There is an exception with the message:

         Cannot use 'SCRIPT' over clusters of connections.

Is there a way to disable the cluster mode to run SCRIPT? Or, is there another way to load a script in Redis (simple single server)?

Thank you very much!
Bruno

**Comment by nrk** [comment]
Clustering is not enabled unless the client is configured to use it, as far as I remember that part shouldn't have changed from v0.8.5 but I can't help you if you don't paste the connection parameters (with the actual ip/port pair obfuscated) and client options used in your application to configure the client instance.

**Comment by brunokk** [comment]
Hi Nrk, thank you for the fast reply! Great job on this important library for php!

I think that I discovered the issue. If you pass an array, even with one single element, it will consider clustering:

$parameters = ['tcp://'.$host.':'.$port."?read_write_timeout=0"];
$options    = ['profile' => '3.0'];
$redisHandle = new Predis\Client($parameters, $options); 

If I use the constructor below with a simple string, it will not consider cluster (as far as the SCRIPT command goes):

$redisHandle = new Predis\Client('tcp://'.$host.':'.$port."?read_write_timeout=0");

It would be nice to have an option in the $options to determine cluster-enabled, but knowing the above, it solves the issue.

Thanks again!
Bruno

**Comment by nrk** [comment]
If you are going to use an array to specify parameters for a single Redis node then you should use a **named array**:

```php
$parameters = ['host' => $host, 'port' => 6379, 'read_write_timeout' => 0]);
```

Plain indexed arrays, even when only one element is specified, are interpreted as a set of connection parameters for multiple nodes which ends up enabling client-side sharding. There's an option to explicitly enable clustering but it's more useful to specify which kind of clustering to use (plain old client-side sharding or redis-cluster) and doesn't really override the above mentioned behaviour.

**Comment by brunokk** [comment]
Got it. Thanks!
