### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by akshaysrivastava** [nrk/predis#462]
Just tried my first with the client and it came up with

Fatal error: Uncaught Error: Class 'Predis\Configuration\Options' not found in /Library/WebServer/Documents/redis/3/src/Client.php on line 74

Error: Class 'Predis\Configuration\Options' not found in /Library/WebServer/Documents/redis/3/src/Client.php on line 74

What might be the reason?

**Comment by nrk** [comment]
Since you didn't describe in detail how you tried to load Predis in your scripts I can't tell what's wrong. Just use [composer](https://getcomposer.org/) anyway, it's the most sensible and trouble-free way to manage your dependencies and load PHP libraries.
