### ISSUE TITLE
source code  question

### ISSUE THREAD

**Issue by lhfeng** [nrk/predis#463]
hello ，

I understand pipeline is that once I/O, many commands, but i read source code, 
 ```
protected function executePipeline(ConnectionInterface $connection, \SplQueue $commands)
    {
        foreach ($commands as $command) {
            $connection->writeRequest($command);
        }

        $responses = array();
        $exceptions = $this->throwServerExceptions();

        while (!$commands->isEmpty()) {
            $command = $commands->dequeue();
            $response = $connection->readResponse($command);

            if (!$response instanceof ResponseInterface) {
                $responses[] = $command->parseResponse($response);
            } elseif ($response instanceof ErrorResponseInterface && $exceptions) {
                $this->exception($connection, $response);
            } else {
                $responses[] = $response;
            }
        }

        return $responses;
    }
```

pipeline is many I/O,many commands, because source code has many write and read.
Is there anything wrong with my understanding?

**Comment by nrk** [comment]
@lhfeng pipelining does not change the request/response nature of Redis, it just makes it possible to drastically cut down the inherent network round-trip time (latency) by sending all of the write I/O operations to the server and read back all the replies to those commands at once. The topic of how pipelining works is [explained quite extensively](https://redis.io/topics/pipelining) in the official Redis documentation, Predis basically implements that.
