### ISSUE TITLE
ConnectionException in AbstractConnection.php line 155

### ISSUE THREAD

**Issue by maxing1005** [nrk/predis#470]
hello,我使用thinkPHP框架加载扩展predis，加载完成后，我使用代码测试
 public function ceShi(){
        \Predis\Autoloader::register();
        $redis = new \Predis\Client();
        $redis->set('redis','111');
        $result = $redis->get('redis');
        return $result;
    }
然后报错
 ConnectionException in AbstractConnection.php line 155
/**
     * Helper method to handle connection errors.
     *
     * @param string $message Error message.
     * @param int    $code    Error code.
     */
    protected function onConnectionError($message, $code = null)
    {
        CommunicationException::handle(
            new ConnectionException($this, static::createExceptionMessage($message), $code)
        );
    }
我通过相应文件路径去找\vendor\predis\predis\src\Connection\ConnectionException.php的文件希望得到帮助，打开后发现是个空类。
我尝试者通过浏览器搜索和网站搜索解决，但是没有解决掉，所以冒昧打扰，希望您能给一些改进的意见。

**Comment by nrk** [comment]
Not sure where you got the impression that I can understand Chinese but... no, I don't understand Chinese. Please write in English here.
