### ISSUE TITLE
Predis setTimeout ? 

### ISSUE THREAD

**Issue by PuShaoWei** [nrk/predis#472]
Hello 
Excuse me, please ，Predis supports setTimeout

**Comment by redisman** [comment]
yes

**Comment by nrk** [comment]
Just create the client using connection parameters such as `timeout` (for the `connect()` operation) and/or `read_write_timeout` (for the timeout of read and write operations over the network) with values expressed in seconds.

**Comment by markhughes** [comment]
@nrk referring to this:
https://github.com/phpredis/phpredis#expire-settimeout-pexpire

**Comment by markhughes** [comment]
Found #403 but it doesn't seem to explain how to use it with predis?

**Comment by markhughes** [comment]
The function is `setex`

```
 * @method int    setex($key, $seconds, $value)
```
