### ISSUE TITLE
what kinds of connection exception can't be discovered

### ISSUE THREAD

**Issue by RootYQ** [nrk/predis#477]
hi, nrk.  I got some troubles when I used sentinel mode.

the specific situation is I get the 'No sentinel server available for autodiscovery' exception when the all redis server can't connect, but how can I find way to realize what kinds of connection exception leads to this problem

```
SENTINEL_QUERY: {
            $sentinel = $this->getSentinelConnection();

            try {
                $slavesParameters = $this->querySentinelForSlaves($sentinel, $this->service);

                foreach ($slavesParameters as $slaveParameters) {
                    $this->add($this->connectionFactory->create($slaveParameters));
                }
            } catch (ConnectionException $exception) {
                $this->sentinelConnection = null;

                goto SENTINEL_QUERY;
            }
        }
```

sorry for my poor English, look forward you reply

**Comment by halleystar** [comment]
oh. I have the same question. but I am  sure that my sentinel is ok and net is ok also.

**Comment by nrk** [comment]
Not sure if this is the answer to your question, but when there are no more sentinel servers available or configured, the library [throws an instance of `Predis\ClientException`](https://github.com/nrk/predis/blob/v1.1.1/src/Connection/Aggregate/SentinelReplication.php#L264-L276).

**Comment by pawansgi92** [comment]
> behaviour

So how we can catch it.
