### ISSUE TITLE
executing predis pubsub example in browser

### ISSUE THREAD

**Issue by kashifali2007** [nrk/predis#482]
i have downloaded predis library from [gitHub](https://github.com/nrk/predis) and trying to execute pubsub [example](predis/examples/pubsub_consumer.php). when i open this file in browser; connection with redis server established successfully, and redis client ready. Once i subscribe to channel, then subscribe loop started. When any message published to that channel from any other redis client, then this message not showing same time but shows when script execution in browser finish, I want to show the message in browser at same time once its received.Further i run the same script (pubsub example) in CLI Mode, in CLI mode, published message showing instantly...Please guide me, can i achieve this message display (show as received) in browser..

**Comment by nrk** [comment]
Depending on how PHP is configured and what your script does, it's most likely a matter related to [output buffering](https://stackoverflow.com/questions/2832010/what-is-output-buffering). Anyway I'm closing this issue since it's unrelated to Predis, you should find a solution on that link.
