### ISSUE TITLE
php redis lua   'attempt to call field 'insert' (a nil value)'  is wrong

### ISSUE THREAD

**Issue by echoBallon** [nrk/predis#492]
1. the redis version is 4.06  on predis is not work and the framework is 'laravel'.
`      $lua =   <<<LUA
string.split = function(s, p)
    local rt= {}
    string.gsub(s, '[^'..p..']+',
        function(w) table.insert(rt, w) end )
    return rt end
return string.split('abc,bcd',',')
LUA;
     return   $logDataSerialize=    Redis::eval($lua,0);
`
the wrong '{
    "message": "ERR Error running script (call to f_c92157f3e89b6e41895a91aaf86ad234d580dbdc): @user_script:4: user_script:4: attempt to call field 'insert' (a nil value) ",
    "status_code": 500
}'
2.i try it on redis-cli is work.
the code 
'eval "string.split = function(s, p) local rt= {} string.gsub(s, '[^'..p..']+', function(w) table.insert(rt, w) end ) return rt end return string.split('abc,bcd',',')" 0'
3.i try  1   redis vesion is 3.0 is work.

thinks , i english is not good.

**Comment by echoBallon** [comment]
then  i restart redis  and is work

**Comment by echoBallon** [comment]
but i dont know why

**Comment by nrk** [comment]
Sorry but I can't give support on issues unrelated to Predis. The error happened on Redis side while running the Lua script as clearly stated on the returned `-ERR` response, the fact that you can't reproduce the issue unfortunately doesn't help.

**Comment by echoBallon** [comment]
thanks
