### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by ankushktr** [nrk/predis#493]
Hi when we create a script in php file as example below we get exceptions of connection 

require "predis/autoload.php";
Predis\Autoloader::register();
$client = new Predis\Client(array(
    'scheme'   => 'tcp',
    'host'     => '127.0.0.1',
    'port'     => 6379
));
echo ($client->exists('message')) ? "test" : "dummy data";

Fatal error: Uncaught Predis\Connection\ConnectionException: Connection refused [tcp://127.0.0.1:6379] in /opt/lampp/htdocs/get/predis/src/Connection/AbstractConnection.php:155 Stack trace: #0 /opt/lampp/htdocs/get/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError('Connection refu...', 111) #1 /opt/lampp/htdocs/get/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://127.0.0.1...', 4) #2 /opt/lampp/htdocs/get/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters)) #3 /opt/lampp/htdocs/get/predis/src/Connection/AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource() #4 /opt/lampp/htdocs/get/predis/src/Connection/StreamConnection.php(258): Predis\Connection\AbstractConnection->connect() #5 /opt/lampp/htdocs/get/predis/src/Connection/AbstractConnection.php(180): Pre in /opt/lampp/htdocs/get/predis/src/Connection/AbstractConnection.php on line 155

Can you resolve this problem please ?This exception occur when we use redis commands like set,get,exist etc

**Comment by nrk** [comment]
If you get a "connection refused" error it means redis is not running on the local computer or it's not listening on 127.0.0.1:6379. Predis by default uses lazy connections so it tries to initialize the connection only on the first command, that's why you get the error when doing `$client->exists()` or any other Redis command.

**Comment by flik** [comment]
Here is solution: https://rapidsol.blogspot.com/2018/10/php-fatal-error-uncaught.html
