### ISSUE TITLE
ErrorException: The each() function is deprecated. 

### ISSUE THREAD

**Issue by jackyxie** [nrk/predis#496]
As I use hscan, by using new Iterator\HashKey(), showup that each() function is deprecated.

PHP version: 7.2
predis version: 1.1.1 install through composer

**Comment by nrk** [comment]
That was actually [fixed quite a long time ago](https://github.com/nrk/predis/commit/157f658f0be5f48cb2aaa4b6a6ac753c1168f465#diff-de6a8311eb47d9085b06cc32047c65cb) but, admittedly, it din't make into a patch release yet so it's only available in `v1.1.x-dev`. Guess it's time to remedy the lack of releases on my part, in the meanwhile you could try by using the dev version until there's a new patch release available (I'll probably just release v1.1.2 as-is sometime this weekend).

**Comment by jackyxie** [comment]
Yeah, I use the dev, and goes well. Thanks. Hope to see the next stable release.

**Comment by szepeviktor** [comment]
> (I'll probably just release v1.1.2 as-is sometime this weekend).

Thank you!

**Comment by jblotus** [comment]
Has there been any movement on this issue? Will there be a release at some point?

**Comment by aedart** [comment]
I too am experiencing this. Is there someone that has the time to create a PR and fix this asap?

**Comment by j0k3r** [comment]
Any news about the v1.1.2?

**Comment by tillkruss** [comment]
This was fixed in 157f658.
