### ISSUE TITLE
Segmented raw command issue

### ISSUE THREAD

**Issue by matijaboban** [nrk/predis#501]
Predis: 1.1.1
Redis: 4.0.8
PHP: 7.2.3
OS: Ubuntu 16.04.4

I've experienced this issue with the fairly new (for this package at least) RediSearch module (http://redisearch.io/) via the PHP client (https://github.com/ethanhann/redisearch-php).

As the RediSearch syntax is more sensitive to command/parameter (arguments) grouping, passed commands do not yield desired results.

For example, when utilizing the PHP client or even passing the parameters as a raw command syntax:

```
...->client->executeRaw([
                'FT.AGGREGATE',
                'restaurants:search',
                '*',
                'GROUPBY 1 @city_id',
                'REDUCE COUNT 1 @city_id AS c_id_count',
                'SORTBY 2 @c_id_count DESC',
                'LIMIT 0 3'
            ]) 
```

yields this raw command:
`"FT.AGGREGATE" "restaurants:search" "*" "GROUPBY 1 @city_id" "REDUCE COUNT 1 @city_id AS c_id_count" "SORTBY 2 @c_id_count DESC" "LIMIT 0 3"`

Which returns improper results. 

The proper syntax via CLI that yields desired results would be:
`FT.AGGREGATE restaurants:search "*" GROUPBY 1 @city_id REDUCE COUNT 1 @city_id AS c_id_count SORTBY 2 @c_id_count DESC LIMIT 0 3`
or
`FT.AGGREGATE restaurants:search * GROUPBY 1 @city_id REDUCE COUNT 1 @city_id AS c_id_count SORTBY 2 @c_id_count DESC LIMIT 0 3`

Is there any possibility of dropping the quotation marks in these cases, when the buffer gets written?

**Comment by nrk** [comment]
Hi @mattboban,

I guess that the double quotes you see are the output of `MONITOR` from the cli and those are only a cosmetic addition to highlight the various parameters of a command. In this case the way you are using parameters is exactly where you problem lies: you must not use `"GROUPBY 1 @city_id"`, `"REDUCE COUNT 1 @city_id AS c_id_count"`, `"SORTBY 2 @c_id_count DESC"` and `"LIMIT 0 3"` as single strings but you must 
split these as single strings. The correct command is thus:

```php
$client->executeRaw([
    'FT.AGGREGATE',
    'restaurants:search',
    '*',
    'GROUPBY', '1', '@city_id',
    'REDUCE', 'COUNT', '1', '@city_id', 'AS', 'c_id_count',
    'SORTBY', '2', '@c_id_count', 'DESC',
    'LIMIT', '0', 3'
]);
```
I'm not sure how the redisearch-php library works internally, but that's the correct way to issue a raw command with Predis.
