### ISSUE TITLE
请问怎么带密码建立Redis连接？

### ISSUE THREAD

**Issue by lxlin315** [nrk/predis#506]
Redis服务端访问设置了密码的，直接通过$redis = new Predis\Client('tcp://127.0.0.1:6379');这样的代码提示“ERR Client sent AUTH, but no password is set”，用这个代码 $redis->auth(‘password’);没用，请问我需要怎么处理？

**Comment by lxlin315** [comment]
找到解决方案了，这是写法之一：
$redis = new Predis\Client(array(
            'scheme'   => 'tcp',
            'host'     => '127.0.0.1',
            'port'     => 6379,
            'database' => 15,
            'parameters'=>[
                'password' => 'DpxWMgwkQnf9CNIi'
            ]
        ));

**Comment by Baachi** [comment]
Hey @lxlin315, if you want help you should wrote your issue in english, because english understand most peoples here.

Second advise, don't post you password on GitHub.

**Comment by lxlin315** [comment]
OK，Thanks！
