### ISSUE TITLE
Error while reading line from the server

### ISSUE THREAD

**Issue by carltondickson** [nrk/predis#507]
We're seeing the following error quite a lot in our application and struggling to understand why 

```
Error while reading line from the server. [tcp://aws-domain:port] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 0): Error while reading line from the server. [tcp://aws-domain:port] at /app/vendor/predis/predis/src/Connection/AbstractConnection.php:155)"} [] 
```

Do you have any tips on how to debug this sort of issue to see what the cause was? We have full stack traces in Sentry but there doesn't seem to be a pattern of when the error occurs.

Things we've tried

* Set the redis.default.read_write_timeout value to 0 in Laravel (/config/database.php)
* Disabled `php artisan horizon:snapshot`, this almost always resulted in the error appearing

Setup
- Heroku Redis (Hobby dev)
- laravel/laravel (5.5.40) d724ce0aa61bbd9adf658215eec484f5dd6711d6
- laravel/horizon (v1.2.3) 36ef9e2d6e09e617cf801050326a69e876ff5535
- predis (v1.1.1) f0210e38881631afeafb56ab43405a92cafd9fd1
- PHP 7.2.5 (cli) (built: Apr 25 2018 03:07:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.5, Copyright (c) 1999-2018, by Zend Technologies

**Comment by carltondickson** [comment]
Manged to log meta data following a communication exception
```
{
  "metadata": {
    "timed_out": false,
    "blocked": true,
    "eof": false,
    "stream_type": "tcp_socket/ssl",
    "mode": "r+",
    "unread_bytes": 0,
    "seekable": false
  }
}
```

**Comment by romilgoel** [comment]
I am also getting error "Error while writing bytes to the server. [tcp://<IP>]". 
What can be the possible areas where I need to debug things ?

**Comment by carltondickson** [comment]
@romilgoel I'm not the best person to ask but based on findings over the last few days check that your Redis server has enough space.

I'm using Heroku Redis and finding that the hard limits (for Redis client connections and memory) can cause things to not work when deployed as they do locally.

**Comment by JayenLee** [comment]
I also encountered this problem, including setting read_write_timeout to 0 and so on, but it has not been solved.

**Comment by JonoHall** [comment]
I'm developing using the Laravel + Horizon framework and deploying to a Redis To Go nano plan through Heroku and was experiencing these issues along with some other "maximum connection" errors. 

I tried reducing connection numbers, which helped a bit, but still having these "reading line" issues.

I ended up ditching the free "Redis To Go" nano plan for redislabs.com and their free 30 MB cache plan which includes 30 connections (up from 10).

This has solved my "line reading" and connection limit issues.

**Comment by carltondickson** [comment]
@JonoHall, thanks for the input. I've never seen this issue locally which is annoying.

Also running horizon on web Dyno...thought this may be a problem but even on worker dynos I still see the error.

Moving to AWS soon and SQS so this will hopefully be a non issue.

**Comment by carltondickson** [comment]
So this seemed to stop the errors from occurring across all of our environments

`heroku redis:timeout --seconds=0 --app=app-name`

I think the Heroku default is 300 seconds, which might explain why I never saw this locally (redis.conf has timeout=0)

```
# config/database.php
    'redis' => [

        'client' => 'predis',

        'default' => [
            'host' => XXX,
            'password' => XXX,
            'port' => XXX,
            'database' => 0,
            'read_write_timeout' => -1,
        ],

    ],
```
Production took a while to settle down - perhaps there were some connections still waiting to be closed or something?

**Comment by romilgoel** [comment]
I got the resolution to the problem. So, there is a limit to ports that a application server can connect to a particular application on another machine. These ports were getting exhausted. 
We increased the limit and the problem got resolved.

How we got to know about this problem ?
In php, we were getting "Cannot assign requested address" error while creating a socket (error code 99).

**Comment by keevitaja** [comment]
https://github.com/laravel/framework/issues/25039#issuecomment-491541751

perhaps predis should check if the connection is still alive for each new request?

**Comment by msonowal** [comment]
Is anybody able to subscribe for aws elasticache for infinite time?

**Comment by roberttolton** [comment]
Unfortunately I haven't had any luck with setting the `read_write_timeout` to `0` or `-1` as when I do so, my whole app immediately `Error 500`'s. Any other solutions?

**Comment by msonowal** [comment]
@roberttolton 
I have done multiple combination of configuration changes but it does not work in any way.
So I have left with elasticache for my realtime server side subscription

**Comment by mezuky04** [comment]
I tried to set `read_write_timeout` to `0` or `-1` and I'm also getting `Error 500` in Horizon.

**Comment by finndev** [comment]
We are also using a managed redis instance from Digitalocean and are facing the same issue.

**Comment by cameeob2003** [comment]
Having the same issue with DigitalOcean managed redis. For now I simply bumped the timoute up to 5 minutes which should help reduce the number of errors but not confident it will fix the issue.

**Comment by cameeob2003** [comment]
I was able to fix this issue by switching to phpredis. Had to prefix the url to my managed DigitalOcean redis instance with tls:// but other than that everything seems to be functioning just fine. May not be solution I was hoping for but at least it works without error now.

**Comment by homeoftheunits** [comment]
You can add the scheme to the redis config in the config/database.php:
```
'redis' => [

        'client' => 'predis',

        'default' => [
            'scheme' => 'tls',
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', 6379),
            'database' => 0,
        ],

    ],
```

**Comment by skors** [comment]
We had the same issue with forked processes and redis connection with predis. `read_write_timeout = -1` also did not work. 

Solution for us was to disconnect predis connection in the forked process and let Predis start a new connection.

**Comment by MPJHorner** [comment]
We had been having issue.
After check the above and also checking our predis version change, it turns out it was just that we had been filling all the memory.
We had been using Laravel and our TTL for sessions was way to high + some DDOS attack meant it was completely full.
Either drop the TTL to 1 day so all those attack sessons drop off or increase the memory should do the trick. 👍

**Comment by Ben-Mack** [comment]
On Windows, if you have Kaspersky installed, disable `Network Attack Blocker` will fix it.

I've tried both Predis and PhpRedis but still error:
`read error on connection to 127.0.0.1:6379` or `Error while reading line from the server. [tcp://127.0.0.1:6379]`

The only way is disable Network Attack Blocker (Kaspersky doesn't even show any events in report, but it blocks redis somehow)
