### ISSUE TITLE
The "get" method do not synced with Redis extension

### ISSUE THREAD

**Issue by ZhukV** [nrk/predis#517]
Hi, we found the problem with using `get` method. In original documentation, the method `get` returns `false` if the key does not exist in service. But the `PRedis` library returns `NULL`.

I think what the `library` should be synced with all return types with original `extension`.

```php
<?php

namespace Acme;

use Predis\Client;

include_once __DIR__.'/vendor/autoload.php';

$client = new Client('redis://redis:6379');
$client->connect();

var_dump($client->get('some-foo-bar'));

$redis = new \Redis();
$redis->connect('redis');

var_dump($redis->get('some-foo-bar'));

```

Result:

```bash
$ root@82b65207bed9:/code# php test.php 
NULL
bool(false)
$ root@82b65207bed9:/code# 
```

**Comment by nrk** [comment]
As per Redis documentation for the [GET command](https://redis.io/commands/get#return-value):

`Bulk string reply: the value of key, or nil when key does not exist.`

Which is the reason why Predis returns NULL when the key does not exists, it doesn't make sense to return FALSE.
