### ISSUE TITLE
redis::sscan ERR Syntax error on Cloud 9 

### ISSUE THREAD

**Issue by jh3er** [nrk/predis#518]
im using this code to return several ticket from a set

`dd($redis->sscan('events:AsKOqWYfnovmheYF9Vi6w4P0H5bIJXXz:tickets' , null ,'*:VIP'));`

it works properly on my computer (localhost) and give me this return value on postman :
```
array:4 [
  0 => "Ct1yaZ2Q0Z:VIP Ticket"
  1 => "5vXsIqYvpF:VIP Ticket"
  2 => "jwCEU0lDXX:VIP Ticket"
  3 => "1mloEc8bFW:VIP Ticket"
]
```

however same code on cloud9 but it returns an error says Server Exception : 

> ERR syntax error
> --
> in Client.php line 370

but when there is no data in the set it return like this :
```
array:2 [
  0 => "0"
  1 => []
]
```

instead of just empty array like this : []

**Comment by nrk** [comment]
Hi @jh3er,

Honestly I'm not sure how it was even working on your local machine, but the correct way to use `SSCAN` with Predis is:

- by following the exact same signature defined by the Redis documentation:

```php
$redis->sscan('events:AsKOqWYfnovmheYF9Vi6w4P0H5bIJXXz:tickets', 0, 'MATCH', '*:VIP');
```

- by following the Predis-specific signature:

```php
$redis->sscan('events:AsKOqWYfnovmheYF9Vi6w4P0H5bIJXXz:tickets', 0, ['match' => '*:VIP']);
```
