### ISSUE TITLE
INCR issues

### ISSUE THREAD

**Issue by andreaschrist27** [nrk/predis#523]
Hi, i'm new in redis. 
it should incr+1. but when i click refresh button in browser INCR+2.  from 1 to 3. is there something wrong ?

![image](https://user-images.githubusercontent.com/14123632/44945831-1ab1a580-ae1b-11e8-9e24-c25f1e9b0166.png)

![image](https://user-images.githubusercontent.com/14123632/44945838-2dc47580-ae1b-11e8-81e6-9ba7256ca020.png)

![image](https://user-images.githubusercontent.com/14123632/44945844-374ddd80-ae1b-11e8-9726-1562558927bb.png)

Thank you :)

**Comment by nrk** [comment]
Maybe it's just the browser asking for two resources when loading / reloading the page (e.g. the browser asks for actual homepage and the favicon filve), anyway it's definitely not something related to Predis or Redis.
