### ISSUE TITLE
Connection error with url as rediss://

### ISSUE THREAD

**Issue by dlorenzomop** [nrk/predis#535]
Hello,
I try to connect to a remote redis database with an URL as :
$bdd_redis = new Predis\Client('**rediss://id:pwd@redis.xxxx.xxxx:port**');
I obtains this error :
Got error 'PHP message: PHP Fatal error: Uncaught Predis\\Connection\\ConnectionException: **Error while switching to encrypted communication** [rediss://xxxxxxx:nnnn] in /home/vcap/app/htdocs/include/predis/src/Connection/AbstractConnection.php:155
 
What would be the origin of this error ?
I tried to find this error message but could not find an answer ...

**Comment by tillkruss** [comment]
You need to use `tls://`.

**Comment by nrk** [comment]
@tillkruss actually both [`redis://`](https://www.iana.org/assignments/uri-schemes/prov/redis) (for plain connections) and [`rediss://`](https://www.iana.org/assignments/uri-schemes/prov/rediss) (for encrypted connections) are accepted schemes and they basically do the same of `tcp://` and `tls://`, albeit with slightly different rules for interpreting the URI as defined by their respective IANA provisional documents.

That said, I guess there's no real way to know why [`stream_socket_enable_crypto()`](https://www.php.net/manual/en/function.stream-socket-enable-crypto.php) fails as reported by @dlorenzomop ([this is the portion of code](https://github.com/nrk/predis/blob/81c0a8f051c74a2e01a29a352b07bf6ffbe20a25/src/Connection/StreamConnection.php#L246-L248) where that exception is raised), it could be [related to this](https://www.php.net/manual/en/function.stream-socket-enable-crypto.php#119122) maybe but objectively it's hard to tell without knowing which version of PHP was being used and how the SSL tunnel was configured. 

`crypto_type` can be specified through connection parameters using the `ssl` dictionary, so it would be easy to try that out just in case we have a way to reproduce the issue.

**Comment by wgxo** [comment]
I was getting the same `Error while switching to encrypted communication` until I used the following configuration.

```php
$redis = new \Predis\Client([
                'scheme'   => 'tls',
                'host'     => $container->get('redisHost'),
                'port'     => $container->get('redisPort'),
                'password' => $container->get('redisPassword'),
                'ssl'      => [
                    'verify_peer'       => false,
                    'verify_peer_name'  => false,
                    'allow_self_signed' => true,
                    'crypto_type' => STREAM_CRYPTO_METHOD_ANY_CLIENT,
                ],
            ]);
```

**Comment by domfie** [comment]
I had `'verify_peer_name'  => false,` but was missing `'verify_peer'       => false,`. Thank you :)

**Comment by SuvanX** [comment]
'crypto_type' => STREAM_CRYPTO_METHOD_ANY_CLIENT,
thanks

**Comment by joehorsnell** [comment]
> I was getting the same `Error while switching to encrypted communication` until I used the following configuration.
> 
> ```
> $redis = new \Predis\Client([
>                 'scheme'   => 'tls',
>                 'host'     => $container->get('redisHost'),
>                 'port'     => $container->get('redisPort'),
>                 'password' => $container->get('redisPassword'),
>                 'ssl'      => [
>                     'verify_peer'       => false,
>                     'verify_peer_name'  => false,
>                     'allow_self_signed' => true,
>                     'crypto_type' => STREAM_CRYPTO_METHOD_ANY_CLIENT,
>                 ],
>             ]);
> ```
> 
> See: https://www.php.net/manual/en/function.stream-socket-enable-crypto.php

You shouldn't ever do this (disable host verification by setting `verify_peer` and/or `verify_peer_name` to `false`), as it undermines the whole point of TLS - you aren't verifying what you're connecting to.

The solution is to establish why the host verification is failing, which will most likely be one or more of the following:
- The server certificate's [CN](https://support.dnsimple.com/articles/what-is-common-name/) does not match the hostname of the connection
- The server cert is not trusted, i.e. signed by a cert in the chain to the trusted root
- The server cert has expired
