### ISSUE TITLE
2 warnings PHP

### ISSUE THREAD

**Issue by Camilo517** [nrk/predis#540]
Hello :)
redis-cache/includes/predis/src/Collection/Iterator/HashKey.php
53 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead

redis-cache/includes/predis/src/Collection/Iterator/SortedSetKey.php
53 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead

**Comment by jimbonator** [comment]
One of these warnings was reported in #496.

**Comment by tillkruss** [comment]
Fixed in 157f658.
