### ISSUE TITLE
Improved fallback for EVAL

### ISSUE THREAD

**Issue by Ejz** [nrk/predis#548]
Is it possible within Predis fallback to `SCRIPT LOAD` + `EVALSHA`, if `EVAL` fails?

**Comment by nrk** [comment]
Hi @Ejz,

When using the Lua scripting abstraction by extending [`Predis\Command\ScriptCommand`](https://github.com/nrk/predis/blob/v1.1.1/examples/lua_scripting_abstraction.php) to define your own _virtual_ and Lua-based command, Predis handles everything for you as it tries to use `EVALSHA` and transparently retries by using `EVAL` (which is basically the same of doing `SCRIPT LOAD` + `EVALSHA` with one less round-trip) when Redis returns a `-NOSCRIPT` response.

On the other hand when using the bare `EVAL` and `EVALSHA` commands you must roll your own logic to handle such cases by replicating the same behaviour, as the client has no way to keep track of the original Lua scripts defined by yourself.
