### ISSUE TITLE
how to use redis bloom filter in predis?

### ISSUE THREAD

**Issue by y80x86ol** [nrk/predis#555]
Hi!
I used predis in my project and install redisbloom for my redis, but i can't use redisbloom command in predis.

I used `$redis->command('bf.add',['test_key','test_value'])` in my code, but it just echo 'Command 'BF.ADD' is not a registered Redis command.'

I want to know how to use redisbloom in predis?

Thanks!

**Comment by David-Gilman** [comment]
Any follow up on this?

**Comment by liutwodog** [comment]
I have also encountered such a problem. Is there any solution

**Comment by Super-DoXCDH** [comment]
You can try to write one yourself in setbit.

**Comment by nrk** [comment]
Hi @y80x86ol,

You should be using the method `Predis\Client::executeRaw()` in such cases when trying to use a command which is not defined by Predis (which can be a common case with Redis modules). Just to use your own snippet, that would look like this:

```php
$client->executeRaw(['bf.add', 'test_key', 'test_value']);
```
