### ISSUE TITLE
[Question] Compatibility with PHP => 7.2

### ISSUE THREAD

**Issue by Maikuolan** [nrk/predis#558]
I've never used Predis before, and I'm not particularly familiar with it (i.e., I know what it is, have read the README and such, but that's about it). I'm currently doing some light, cursory research into various bindings, extensions and such for some possible ideas for a future project. Latest Travis build for Predis indicates compatibility with PHP versions => 5.3 <= 7.1 and HHVM, but doesn't specifically test against PHP => 7.2 (there are, of course, some pending pull requests to include this). I haven't yet downloaded/installed/tested Predis. Just wanting to ask quickly (an easy question, I imagine, for anyone familiar with Predis, and a yes/no answer should suffice), whether Predis is compatible with PHP => 7.2? Cheers. :-)

**Comment by GrahamCampbell** [comment]
https://github.com/nrk/predis/pull/537

**Comment by GrahamCampbell** [comment]
Seems to pass every test that 7.1 passed.

**Comment by Maikuolan** [comment]
@GrahamCampbell Cheers. :-)

I've finished my aforementioned cursory research now, so I consider this resolved; Closing accordingly.
