### ISSUE TITLE
New stable release - needed for PHP 7.3

### ISSUE THREAD

**Issue by mvorisek** [nrk/predis#564]
The last release in in 2016, can a new stable release be expected?

I am asking primary as the HEAD of the `master` branch is compatible with PHP 7.3, but the latest release `1.1.1` is not.The latest stable version is used by many packages making them effectively not usablee for PHP 7.3.

At least this bugfix is missing in the latest release: https://github.com/nrk/predis/pull/448

**Comment by gries** [comment]
Can we please get that release tagged?
I really would like to avoid having to fork + tag that repo.

**Comment by tillkruss** [comment]
v1.1.2 will go out this week 👍🏻
