### ISSUE TITLE
Wiki link broken

### ISSUE THREAD

**Issue by adjenks** [nrk/predis#570]
![image](https://user-images.githubusercontent.com/10687569/61984201-30dace00-afb8-11e9-865c-2376e3d3da17.png)
![image](https://user-images.githubusercontent.com/10687569/61984207-39cb9f80-afb8-11e9-88be-92677dba5686.png)

**Comment by xemose** [comment]
Wiki link should be fixed to https://github.com/nrk/predis/wiki

**Comment by MeroveeCharrue** [comment]
There is an open PR to fix exactly this : #589.
