### ISSUE TITLE
predis StreamConnection::createStreamSocket chokes on large redis servers with read replicas

### ISSUE THREAD

**Issue by abbood** [nrk/predis#581]
currently my laravel app uses predis to connect just fine to redis on aws elastic cache, i'm using a single m4.10xlarge instance (154 GB memory). things are ok.

The only problem is that the above instance is very expensive ($2,764/month):
<img width="574" alt="big" src="https://user-images.githubusercontent.com/774379/64316905-d7a28900-cfbe-11e9-8465-f1deb04a2719.png">

 it would be cheaper (and actually have more horse power) to use a single instance of m4.2xlarge and give it two replicas ($1,657):
<img width="574" alt="small" src="https://user-images.githubusercontent.com/774379/64316939-f1dc6700-cfbe-11e9-8c55-67217a51a62a.png">

However, as soon as i deployed this new setting on production, latency shot up. I investigated the cause on new relic and found that it was StreamConnection::createStreamSocket:

![image](https://user-images.githubusercontent.com/774379/64317094-526ba400-cfbf-11e9-938c-736afa90ae80.png)

Am i doing something wrong? or is this an inherent problem with predis?

**Comment by KeithBush** [comment]
The slow method mentioned appears to just open a standard php socket with a default of 5 seconds.
This means you have a problem where PHP is having trouble opening a socket or communicating on that socket to your redis server.  The 5 second duration is in line with the socket timeout as well.

Predis throws a `ConnectionException` if it fails to connect.
Make sure you aren't catching all exceptions and ignoring them. You probably want to log or notify yourself if ConnectionException gets thrown so you know you need to fix redis.

You should be able to test redis from the terminal of the web server; make sure it can connect and interact with your redis cluster. 
If you can't access redis from the terminal, check your firewall rules. 
If you can access redis from the terminal, check that the connection details provided to predis are correct and check your php settings for any socket limitations.

**Comment by nrk** [comment]
Hi @abbood,

I don't have much to add to @KeithBush's comment as it pretty much sums everything up.

Just wanted to say that you can try forcing the client to open a connection by using `Predis\Client::connect()` and catching `Predis\ConnectionException` to capture any error that might occur when PHP opens the socket stream to the Redis server.
