### ISSUE TITLE
setex is not working correctly if the value is a integer.

### ISSUE THREAD

**Issue by KevinHN** [nrk/predis#584]
Hello,

We have the simple source code like this: 
```
$this->connection()->setex($this->prefix.$key, 15, 1);
$value = $this->connection()->get($this->prefix.$key); // $value is null
```
The value in the redis is nil too.

I try to use redis command `SETEX 15 1 ` it works fine.

My predis version: 1.1.1
Redis version: 3.2.12 (Centos 7)

I hope to hear from you at the earliest!

**Comment by gladx** [comment]
Hi 

I test SETEX and work correctly for me.

```php

$client = new Predis\Client();

$client->setex('a', 15 , 1);

echo $client->get('a');
// 1

echo  $client->ttl('a');
// 15
```

Please debug value of `$this->prefix.$key`

**Comment by nrk** [comment]
Closing this issue as it cannot be reproduced.
As indicated by @gladx, you most likely have some unexpected value from `$this->prefix.$key`.
