### ISSUE TITLE
INFO command disallowed in replication mode 

### ISSUE THREAD

**Issue by mrtronje** [nrk/predis#596]
If we setup redis client to connect via replication mode, the info command is disallowed. The info command should be allowed as it's a valid command in replication mode. Further the info command is important when using the symfony RedisTagAwareAdapter as it's rely on the info command for determine the evicition-policy of redis (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Cache/Adapter/RedisTagAwareAdapter.php#L277)

example to reproduce:
```
$sentinels = ['tcp://120.0.0.1:26378','tcp://120.0.0.2:26378','tcp://120.0.0.3:26378'];
$options = ['replication' => 'sentinel', 'service' => 'mymaster'];
$client = new \Predis\Client($sentinels, $options);
$client->info();
```
If I remove the info command from the disallow-list (https://github.com/nrk/predis/blob/v1.1/src/Replication/ReplicationStrategy.php#L219) the command (`$client->info()`) works like a charm. 

Could we remove the command from the disallow-list? Or make the disallow-list at least configurable?

**Comment by nrk** [comment]
Hi @mrtronje, see [my comment](https://github.com/nrk/predis/issues/598#issuecomment-671876712). We may discuss about eventually changing this behaviour for future releases, anyway if you are interested I suggest you get in touch on #598 so that we can have a single point of discussion. Thank you!
