### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by bart3r** [nrk/predis#597]
Hi,

I am getting the following errors and I can't see a good solution for this problem:

`www: PHP Fatal error:  Uncaught Predis\Connection\ConnectionException: Cannot assign requested address [tcp://127.0.0.1:6379] in /var/www/html/api/shared/vendor/predis/predis/src/Connection/AbstractConnection.php:155#012Stack trace:#012#0 /var/www/html/api/shared/vendor/predis/predis/src/Connection/StreamConnection.php(128): Predis\Connection\AbstractConnection->onConnectionError('Cannot assign r...', 99)#012#1 /var/www/html/api/shared/vendor/predis/predis/src/Connection/StreamConnection.php(178): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Connection\Parameters), 'tcp://127.0.0.1...', 4)#012#2 /var/www/html/api/shared/vendor/predis/predis/src/Connection/StreamConnection.php(100): Predis\Connection\StreamConnection->tcpStreamInitializer(Object(Predis\Connection\Parameters))#012#3 /var/www/html/api/shared/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\Connection\StreamConnection->createResource()#012#4 /var/www/html/api`

If I run **netstat -n | grep TIME_WAIT**, I see thousands of entries like this:

```
tcp        0      0 127.0.0.1:38452         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:54719         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:45938         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:42494         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:56776         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:40567         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:58754         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:48474         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:36836         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:48568         127.0.0.1:6379          TIME_WAIT
tcp        0      0 10.0.0.17:51532         10.0.0.7:9999           TIME_WAIT
tcp        0      0 10.0.0.17:36038         10.0.0.7:9999           TIME_WAIT
tcp        0      0 10.0.0.17:49984         10.0.0.7:9999           TIME_WAIT
tcp        0      0 127.0.0.1:55880         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:54475         127.0.0.1:6379          TIME_WAIT
tcp        0      0 10.0.0.17:44016         10.0.0.7:9999           TIME_WAIT
tcp        0      0 127.0.0.1:39391         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:35082         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:48109         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:43118         127.0.0.1:6379          TIME_WAIT
tcp        0      0 127.0.0.1:32789         127.0.0.1:6379          TIME_WAIT
```

Any clues on where to solve this problem?

**Comment by nrk** [comment]
Hi @bart3r,

Admittedly this is not really specific to Predis, but I think this could be useful anyway.

Having tons of connections in a `TIME_WAIT` state usually means that you are opening new connections so quickly to the point that the limit configured for the kernel is reached, as connection pairs in `TIME_WAIT` cannot be reused until they reach a timeout. Most likely you have a decent amount of traffic on that host.

If you host is running on a Linux kernel you may try a few specific tweaks by using the `sysctl` command line tool, this won't make these settings permanent so this is generally safe as you can just set them back to their original values or simply reboot the host. You can eventually make these settings permanent by adding them to `/etc/sysctl.conf` or to a conf file in `/etc/sysctl.d/` if your distribution comes with systemd.

- `net.ipv4.tcp_tw_reuse`: set this to `1` which enables the kernel to reuse connections in a `TIME_WAIT` state when needed, even before the socket pair timeout is reached.

- `net.ipv4.ip_local_port_range`: this is the pool range of local ephemereal ports that can be used by the system, the default is usually `32768 61000` but you could try increasing this range a bit on the lower end, maybe something like `16384 61000`.

- `net.ipv4.tcp_fin_timeout`: this defines the minimum amount of time socket pairs are kept in a `TIME_WAIT` state, usually the default value is `60` seconds by you may want to try lowering this to something like `30` seconds.

You should try setting `net.ipv4.tcp_tw_reuse` first and proceed with the other settings only if that one wasn't enough. I always suggest reading a bit more in depth about these settings, you can find plenty of documentation about them through search engines.

**Comment by bart3r** [comment]
Yes, it turns out we wrote bad code where we always creating new connections for every cache request, instead of re-using the same connection.
