### ISSUE TITLE
Command 'ROLE' is not a registered Redis command.

### ISSUE THREAD

**Issue by fliespl** [nrk/predis#603]
Hi @nrk - first of all great work on this library :)

Have a question though - is there any reason by which ROLE command is not supported? It's available since Redis 2.8.

**Comment by nrk** [comment]
Hi @fliespl,

The reason why `ROLE` is not directly exposed by the client is that most of the times there's no need to use it and you can still rely on `Predis\Client::executeRaw()` when required. In fact, `ROLE` is internally used by [`Predis\Connection\Aggregate\SentinelReplication`](https://github.com/nrk/predis/blob/v1.1.1/src/Connection/Aggregate/SentinelReplication.php), but we use a raw command. I'm not against exposing it, it's just not a priority right now.
