### ISSUE TITLE
Change license to GPL

### ISSUE THREAD

**Issue by tillkruss** [nrk/predis#623]
Should we change the license to GPL?

**Comment by nrk** [comment]
Sorry, but I'm against this.

**Comment by tillkruss** [comment]
No problem 👍🏻 Could you elaborate why and what you had in mind for the future?

**Comment by nrk** [comment]
The reason is I don't see an actual reason, now or in the future, for such a change.

And to be honest, I personally don't even like GPL (especially v3) and its virality in this context, I think the [MIT license serves it purpose alright](https://www.tawesoft.co.uk/kb/article/mit-license-faq). Most PHP frameworks and many libraries are MIT-licensed after all.

**Comment by tillkruss** [comment]
Yeah, MIT is great, too. I was thinking of this below and just wanted to bring it up for discussion.

>Plugins must be compatible with the GNU General Public License #1. Plugins must be compatible with the GNU General Public License
>
>Although any GPL-compatible license is acceptable, using the same license as WordPress — “GPLv2 or later” — is strongly recommended. All code, data, and images — anything stored in the plugin directory hosted on WordPress.org — must comply with the GPL or a GPL-Compatible license. Included third-party libraries, code, images, or otherwise, must be compatible. For a specific list of compatible licenses, please read the GPL-Compatible license list on gnu.org.

https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#1-plugins-must-be-compatible-with-the-gnu-general-public-license

**Comment by b1rdex** [comment]
MIT License (Expat) is GPL-compatible. You can find it on https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses.

**Comment by nrk** [comment]
@tillkruss as pointed by @b1rdex there are no issues in the specific case of Wordpress, as the MIT (Expat) license is officially considered to be GPL-compatible .

**Comment by tillkruss** [comment]
Stick with MIT.
